# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "10m"

def groupby():
    return ["user"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    process = (event.get('process_name') or '').lower()

    if process in ['uname','id','whoami','sudo','cat']:
        return 0.50

    return 0.0


def clusters(event):



    return session.get("clusterss")

def context(event):
    return (
        "System reconnaissance command " + str(event.get('process_command')) + " executed by user " +
        str(event.get('user')) +
        " on host " + str(event.get('host')) +
        ". This may indicate attacker discovery activity."
    )

def criticality():
    return "MEDIUM"

def tactic():
    return "Discovery (TA0007)"

def technique():
    return "System Information Discovery (T1082)"

def artifacts():
    return stats.collect(["host","user","process_name","process_command","event_details"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("user", "unknown"),
        "type": "username"
    }
