EXCLUDED_IPS = ["103.59.181.11"]

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "2m"

def groupby():
    return ["source_ip"]

def investigate():
    return "windows_network_smb_dns_activity_monitoring"

def automate():

    # automation: windows_network_smb_dns_activity_monitoring
    return True

def notify():
    return False

def algorithm(event):
    event_id = event.get('event_id')
    src_ip = event.get('source_ip')

    if event_id not in ["5152", "5157"]:
          return 0.0

    if not src_ip or src_ip in ["-", "UNKNOWN", None]:
        return 0.0
    src_external = (src_ip not in EXCLUDED_IPS) and (not is_internal_ip(src_ip))
    if not src_external:
        return 0.0

    blocked_count = stats.count("blocked_connections_per_source")  # counts all events in group/window

    if blocked_count > 10:
      return 0.5
    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    src_ip = event.get("source_ip")
    dst_host = event.get("host")
    return (
        "External IP %s generated over 10 blocked firewall connection attempts "
        "to host '%s' within 2 minutes, indicating possible port scanning activity."
    ) % (src_ip, dst_host)

def criticality():
    return "MEDIUM"

def tactic():
    return "Reconnaissance (TA0043)"

def technique():
    return "Network Scanning (T1595)"

def artifacts():
    return stats.collect(["host","source_ip","destination_port","source_port","event_id"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "email"
    }


def is_internal_ip(ip_str):
    if not ip_str:
        return False

    parts = ip_str.split(".")
    if len(parts) != 4:
        return False

    try:
        a, b, c, d = [int(p) for p in parts]
    except ValueError:
        return False

    # Validate range 0-255
    if not (0 <= a <= 255 and 0 <= b <= 255 and 0 <= c <= 255 and 0 <= d <= 255):
        return False

    # Private IP ranges
    if a == 10:
        return True
    if a == 172 and 16 <= b <= 31:
        return True
    if a == 192 and b == 168:
        return True

    # Loopback
    if a == 127:
        return True

    # Link-local
    if a == 169 and b == 254:
        return True

    return False