# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return ["source_account_name"]

def investigate():
    return "windows_account_privilege_management"

def automate():

    # automation: windows_account_privilege_management
    return True

def notify():
    return False

def algorithm(event):
    key = application.get("high_risk_pri")

    # If key is already set, always return 0.0
    if key is True:
        return 0.0

    # Ensure it's Event ID 4672 (Special Logon)
    if event.get('event_id') != "4672":
        return 0.0  # Ignore other events

    # Extract key fields
    user = event.get("source_account_name", "").lower()
    privileges = [priv.lower() for priv in event.get("privileges", [])]

    # List of known system accounts to ignore
    ignored_accounts = ["system", "local service", "network service", "administrator"]

    # List of high-risk privileges
    critical_privileges = [
        "sedebugprivilege",
        "seimpersonateprivilege",
        "setakeownershipprivilege",
        "seloaddriverprivilege"
    ]


    if ("$" in user or user in ignored_accounts or user.startswith("dwm-") or user.startswith("umfd-") or event.get("source_account_domain", "").lower() in ["window manager"]):
      return 0.0

    # Only trigger if high-risk privileges are assigned
    if any(priv in privileges for priv in critical_privileges):
        application.put("high_risk_pri", True, 86400)
        return 0.75
    return 0.0


def clusters(event):



    return session.get("clusterss")

def context(event):
    base = (
        "High-risk admin privileges were assigned to user '{user}' "
        "from domain '{domain}' on device '{host}'.\n\n"
        "Privileges: {privileges}\n"
    ).format(
        user=event.get('source_account_name', 'Unknown'),
        domain=event.get('source_account_domain', 'Unknown'),
        host=event.get('host', 'Unknown'),
        privileges=", ".join(event.get('privileges', []))
    )

    return base

def criticality():
    return "HIGH"

def tactic():
    return "Privilege Escalation (TA0004)"

def technique():
    return "Access Token Manipulation (T1134)"

def artifacts():
    return stats.collect(["source_account_name","privileges","event_id"])

def correlationArtifacts():
    return ["source_account_name","event_id"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }
