# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_powershell_credential_access_activity_monitoring"

def automate():

    # automation: windows_powershell_credential_access_activity_monitoring
    return True

def notify():
    return False

def algorithm(event):
    if event.get('event_id') == "10" and 'lsass.exe' in event.get('target_process'):
        return 1.0
    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    return "Process " + event.get('process_name') + " accessed LSASS memory, possible credential dumping attempt."

def criticality():
    return "CRITICAL"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "OS Credential Dumping (T1003)"

def artifacts():
    return stats.collect(["host","process_name","target_process","event_id"])

def correlationArtifacts():
    return ["process_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("process_name", "unknown"),
        "type": "email"
    }
