# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return ["host"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    path = (event.get('file_path') or '').lower()
    proc = (event.get('process_name') or '').lower()

    key = application.get("registry_runkey_persistence")

    # Prevent duplicate alerts
    if key is True:
        return 0.0

    if not path:
        return 0.0

    # Common Run key locations
    run_keys = [
        'software\\microsoft\\windows\\currentversion\\run',
        'software\\microsoft\\windows\\currentversion\\runonce'
    ]

    # Check for registry-like path
    if not any(rk in path for rk in run_keys):
        return 0.0

    # Optional: suspicious processes modifying registry
    suspicious_procs = ['powershell', 'cmd', 'wscript', 'reg']

    if proc and any(p in proc for p in suspicious_procs):
        application.put("registry_runkey_persistence", True, 3600)
        return 0.75

    return 0.0


def clusters(event):


    return session.get("clusterss")

def context(event):
    path = event_data.get('file_path')
    proc = event_data.get('process_name')
    host = event_data.get('host')
    user = event_data.get('user_name')

    context = "Possible persistence mechanism detected via registry Run key modification "

    if proc:
        context += "by process " + str(proc) + " "

    if user:
        context += "under user " + str(user) + " "

    if host:
        context += "on host " + str(host) + " "

    if path:
        context += "targeting registry path " + str(path) + " "

    context += "Run keys are commonly used by attackers to maintain persistence across system reboots."

    return context

def criticality():
    return "HIGH"

def tactic():
    return "Persistence (TA0003)"

def technique():
    return "Registry Run Keys / Startup Folder (T1547)"

def artifacts():
    return stats.collect(["file_path","process_name","user_name","host"])

def correlationArtifacts():
    return ["host"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
