# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_powershell_credential_access_activity_monitoring"

def automate():

    # automation: windows_powershell_credential_access_activity_monitoring
    return True

def notify():
    return False

def algorithm(event):
    if str(event.get("event_id") or "") != "4688":
        return 0.0

    process = str(event.get("process_name") or "").lower()
    cmd = str(event.get("command_line") or "").lower()
    host = event.get("host")
    redkey = "credential_dumping" + host
    try:
        key = application.get(redkey)
    except Exception:
        key = None

    if key in (True, "true", "True"):
        return 0.0

    indicators = [
        "lsass.exe",
        "mimikatz",
        "sekurlsa::",
        "lsadump::",
        "procdump",
        "comsvcs.dll",
        "minidump",
        "dumpert",
        "nanodump",
        "handlekatz",
        "pypykatz"
    ]
    lock_acquired = application.putifabsent(redkey,True,86400)
    for indicator in indicators:
        if indicator in process or indicator in cmd:
          if lock_acquired:
            return 1.0

    return 0.0


def clusters(event):





    return session.get("clusterss")

def context(event):
    process = event.get("process_name") or "unknown"
    parent = event.get("parent_process_name") or "unknown"
    user = event.get("source_account_name") or "unknown"
    host = event.get("host") or "unknown"
    cmd = event.get("command_line") or "unavailable"

    return (
        "Potential credential dumping activity detected. "
        "Process '{}' was launched by parent process '{}' "
        "under account '{}' on host '{}'. "
        "Observed command line: '{}'. "
        "The process execution contains indicators commonly associated with "
        "credential dumping tools or attempts to access LSASS memory for "
        "credential extraction."
    ).format(
        process,
        parent,
        user,
        host,
        cmd
    )

def criticality():
    return "CRITICAL"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "OS Credential Dumping (T1003)"

def artifacts():
    return stats.collect(["host","process_name","parent_process_name","source_account_name"])

def correlationArtifacts():
    return ["process_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
