# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    action = (event.get("event_action") or "").strip().lower()

    if action == "delete safe":
        return 1.0

    return 0.0


def clusters(event):

    return session.get("clusters")

def context(event):
    user = event.get("user_name") or "Unknown User"
    safe = event.get("safe_name") or "Unknown Safe"

    return (
        "User '{}' deleted CyberArk Safe '{}'. "
        "Deleting a Safe removes access to the privileged credentials stored within it "
        "and should be verified as an authorized administrative action."
    ).format(user, safe)

def criticality():
    return "CRITICAL"

def tactic():
    return "Impact (TA0040)"

def technique():
    return "Data Destruction (T1485/001)"

def artifacts():
    return stats.collect(["user_name","source_ip","source_hostname","applicationname","event_action"])

def correlationArtifacts():
    return ["user_name"]

def huntingQueryTemplate():
    return ""

def entity(event):
    return {
        "derived": False,
        "value": event.get("user_name", "unknown"),
        "type": "user"
    }
