
# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_execution_and_persistence_activity"

def automate():

    # automation: windows_execution_and_persistence_activity
    return True

def notify():
    return False

def algorithm(event):

    if str(event.get('event_id')) != '4698':
        return 0.0

    if _is_system_context(event) and _is_known_benign_task(event):
        return 0.0

    # Only alert if user-created AND suspicious behavior
    if not _is_system_context(event) and _is_suspicious_command(event):
        return 0.5

    return 0.0


def clusters(event):




    return session.get("clusterss")

def context(event):
    return "Scheduled task created by {} on host {}".format(
        event.get('source_account_name'),
        event.get('host')
    )

def criticality():
    return "MEDIUM"

def tactic():
    return ""

def technique():
    return "Scheduled Task/Job (T1053)"

def artifacts():
    return stats.collect(["event_id","host","source_account_name"])

def correlationArtifacts():
    return ["source_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }


def _is_system_context(event):
    user = (event.get('source_account_name') or '').lower()
    logon_id = (event.get('subject_logon_id') or '').lower()

    return (
        user.endswith('$') or              # machine account
        logon_id == '0x3e7' or             # SYSTEM logon session
        user in ['system', 'local service', 'network service']
    )
def _is_known_benign_task(event):
    task_name = (event.get('task_name') or '').lower()
    content = (event.get('task_content') or '').lower()

    return (
        task_name.startswith('\\microsoft\\') and
        'program files' in content
    )
def _is_suspicious_command(event):
    content = (event.get('task_content') or '').lower()

    suspicious_keywords = [
        'powershell',
        'cmd.exe',
        'wscript',
        'cscript',
        'bitsadmin',
        'certutil',
        'mshta',
        'base64',
        'http',
        'https',
        'temp',
        'appdata'
    ]

    return any(k in content for k in suspicious_keywords)