# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "10m"

def groupby():
    return ["query_name","host"]

def investigate():
    return "windows_network_smb_dns_activity_monitoring"

def automate():

    # automation: windows_network_smb_dns_activity_monitoring
    return True

def notify():
    return False

def algorithm(event):
    evt_id = str(event.get("event_id", ""))

    # Sysmon DNS Query Event
    if evt_id != "22":
        return 0.0

    query_name = str(
        event.get("query_name", "")
    ).lower()

    host = str(
        event.get("host", "")
    ).lower()

    if not query_name:
        return 0.0

    # Ignore invalid/noisy values
    invalid_domains = [
        "-",
        "unknown",
        "localhost"
    ]

    if query_name in invalid_domains:
        return 0.0

    # Ignore common noisy/benign domains
    benign_domains = [
        "microsoft.com",
        "windows.com",
        "office.com",
        "bing.com",
        "google.com",
        "gstatic.com",
        "msftconnecttest.com"
    ]
    for domain in benign_domains:

        if domain in query_name:
            return 0.0

    if stats.count('dns_tunneling_query_name_detection') == 51:
        stats.resetcount('dns_tunneling_query_name_detection')
        return 1.0

    return 0.0


def clusters(event):



    return session.get("clusterss")

def context(event):
    query_name = event.get("query_name")
    host = event.get("host",)
    process_name = event.get("process_name")

    return (
        "More than 50 DNS queries for domain '%s' "
        "were observed within 10 minutes on host '%s' "
        "from process '%s'. This activity may indicate "
        "DNS tunneling, beaconing, or command-and-control "
        "communication over DNS."
    ) % (
        query_name,
        host,
        process_name
    )

def criticality():
    return "CRITICAL"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Application Layer Protocol (T1071/004)"

def artifacts():
    return stats.collect(["host","event_id"])

def correlationArtifacts():
    return ["event_id"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("query_name", "unknown"),
        "type": "email"
    }
