# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "10m"

def groupby():
    return ["source_device_name"]

def investigate():
    return "fortigate_system_integrity_monitoring"

def automate():

    # automation: fortigate_system_integrity_monitoring
    return True

def notify():
    return False

def algorithm(event):

    details = str(event.get("event_details") or "").lower()
    device = str(event.get("source_device_name") or "unknown")
    key = application.get("fortigate_fortiAnalyzer")

    if not details:
        return 0.0

    if key in (True, "true", "True"):
        return 0.0

    keywords = [
        "failed to connect fortianalyzer",
        "failed to connect to fortianalyzer",
        "fortianalyzer unreachable",
        "cannot reach fortianalyzer",
        "connection timeout fortianalyzer",
        "fortianalyzer connection failed"
    ]

    if any(k in details for k in keywords):
        count = stats.count("fortianalyzer")
        if count > 3:
            stats.resetcount("fortianalyzer")
            lock_acquired = application.putifabsent("fortigate_fortiAnalyzer", True, 86400)
            if lock_acquired:
              return 0.5

    return 0.0


def clusters(event):









    """
    Store the session
    """
    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    return str(event.get('event_details')) + " for the device " + str(event.get('source_device_name')) + " with more than 3 attempts."

def criticality():
    return "MEDIUM"

def tactic():
    return "Defense Evasion (TA0005)"

def technique():
    return "Impair Defenses (T1562)"

def artifacts():
    return stats.collect(["event_severity","event_action","event_alert","log_subtype","source_ip","destination_ip","source_device_name"])

def correlationArtifacts():
    return ["source_device_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_device_name", "unknown"),
        "type": "host"
    }
