from datetime import datetime

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    process = (event.get('process_name') or '').lower()
    action = (event.get('event_action') or '').lower()
    timestamp = event.get('timestamp')

    if process == 'sshd' and action == 'accepted' and timestamp:
        try:
            dt = datetime.utcfromtimestamp(float(timestamp)/1000)
            hour = dt.hour
            minute = dt.minute
        except:
            return 0.0

        if (
            (hour == 18 and minute >= 30) or
            (hour > 18 and hour < 23) or
            (hour == 23 and minute <= 30)
        ):
            return 0.50

    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    return (
        "Successful SSH login detected during off-hours for user " +
        str(event.get('user')) +
        " on host " + str(event.get('host')) + " from source ip " + str(event.get('source_ip')) + " and port " + str(event.get('source_port')) +  
        ". This may indicate unauthorized access."
    )

def criticality():
    return "MEDIUM"

def tactic():
    return "Initial Access (TA0001)"

def technique():
    return "Valid Accounts (T1078)"

def artifacts():
    return stats.collect(["host","user","source_ip","event_details","source_port","event_action","process_name"])

def correlationArtifacts():
    return ["user","host","source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("user", "unknown"),
        "type": "email"
    }

