# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["source_account_name","process_name"]

def investigate():
    return "windows_authentication_logon_anomalies"

def automate():

    # automation: windows_authentication_logon_anomalies
    return True

def notify():
    return False

def algorithm(event):

    # only failed logons
    if str(event.get("event_id")) != "4625":
        return 0.0

    acct = (event.get("source_account_name") or "").lower()
    process = (event.get("process_name") or "").lower()
    logon_type = event.get("logon_type")

    # focus on service/machine behavior
    is_machine = acct.endswith("$")
    is_service = logon_type in ["4", "5"]

    if not (is_machine or is_service):
        return 0.0
    try:
        key = application.get("windows_service_machonauth_failures")
    except Exception:
        key = None

    if key in (True, "true", "True"):
        return 0.0


    if stats.count("service_auth_failures") > 5:
        stats.resetcount("service_auth_failures")
        lock_acquired = application.putifabsent("windows_service_machonauth_failures",True,86400)
        if lock_acquired:
          return 0.25

    return 0.0


def clusters(event):






    return session.get("clusters")

def context(event):
    acct = event.get("source_account_name") or "unknown service account"
    process = event.get("process_name") or "unknown process"
    host = event.get("host") or "unknown host"
    target = event.get("destination_account_name") or "unknown target"

    return (
        "Repeated authentication failures detected from service or machine account "
        + str(acct)
        + " via process "
        + str(process)
        + " on host "
        + str(host)
        + " while attempting to access account "
        + str(target)
        + ". This may indicate a misconfigured service, expired credentials, or background authentication issues."
    )

def criticality():
    return "LOW"

def tactic():
    return "Persistence (TA0003)"

def technique():
    return "Valid Accounts (T1078)"

def artifacts():
    return stats.collect(["source_account_name","destination_account_name","process_name","host","logon_type","event_id"])

def correlationArtifacts():
    return ["source_account_name"]

def huntingQueryTemplate():
    return """SELECT * FROM dictionary WHERE source_ip = '{{source_ip}}'logon_type
AND event_id ='4625' and logon_type IN ('4', '5')"""

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }
