# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    analysis = stats.zanomaly("network_bytes_transferred")
    session.set("anomalies", [analysis])
    return "Initialized zanomaly detection"

def window():
    return "10m"

def groupby():
    return ["source_ip"]

def investigate():
    return "fortigate_network_traffic_anomaly_detection"

def automate():

    # automation: fortigate_network_traffic_anomaly_detection
    return True

def notify():
    return False

def algorithm(event):
    destination_ip = event.get("destination_ip")
    destination_port = str(event.get("destination_port") or "")
    protocol = str(event.get("network_protocol") or "").upper()
    account_name = event.get("user_name")
    total_bytes = int(event.get("network_bytes_transferred") or 0)

    if not destination_ip or total_bytes <= 0:
        return 0.0

    in_range = cidr.inRange(destination_ip, [
        "14.141.115.58/30",
        "14.142.192.128/30",
        "125.17.69.248/30",
        "61.95.141.98/30",
        "203.194.111.106/32",
        "100.122.137.60/32",
        "100.76.126.248/32",
        "115.111.247.166/30",
        "103.176.170.64/29",
        "103.155.57.72/29",
        "14.140.210.208/30",
        "103.137.218.98/29",
        "122.185.181.54/30",
        "203.112.158.244/29",
        "103.26.201.244/29",
        "103.26.201.252/29",
        "103.26.201.0/24",
        "182.66.121.26/30",
        "14.97.152.142/30",
        "122.186.71.70/30",
        "14.143.159.224/30",
        "122.187.39.102/30",
        "203.122.8.200/29",
        "136.232.144.116/30",
        "136.232.142.132/30",
        "203.200.68.0/24",
        "14.140.162.248/29",
        "125.22.24.16/29",
        "115.112.32.192/29",
        "14.142.33.176/28",
        "59.160.104.0/24",
        "122.187.57.64/27",
        "47.29.213.16/29"
    ])

    if in_range:
        return 0.0

    monitored_ports = ["23", "22", "3389"]
    monitored_protocols = ["ICMP", "TELNET", "SSH", "RDP"]

    condition1 = (
        destination_port == "53"
        or "HTTP" in protocol
        or "HTTPS" in protocol
    )

    condition2 = (
        destination_port in monitored_ports
        or protocol in monitored_protocols
    ) and (
        account_name not in [None, "-", "UNKNOWN", ""]
        and "$" not in str(account_name)
    )

    if not (condition1 or condition2):
        return 0.0

    stats.count("abnormal_outside")
    count = stats.getcount("abnormal_outside")

    analysis = session.get("anomalies")[0]
    anomaly = analysis.get("anomaly")

    if count >= 25 and anomaly == 1:
        stats.resetcount("abnormal_outside")
        return 0.75

    return 0.0

    # destination_ip = event.get("destination_ip")
    # destination_ports = ["23", "22", "3389"]
    # application_protocols = ["ICMP", "TELNET", "ssh", "RDP"]
    # account_name = event.get("user_name")

    # sentbytes = (
    #     int(event.get("network_bytes_out"))
    #     if event.get("network_bytes_out") is not None
    #     else 0
    # )
    # receivedbytes = (
    #     int(event.get("network_bytes_in"))
    #     if event.get("network_bytes_in") is not None
    #     else 0
    # )

    # account_name = event.get("user_name")

    # condition1 = event.get("destination_port") == "53" or (
    #     event.get("network_protocol") is not None
    #     and ("HTTP" in event.get("network_protocol") or "HTTPS" in event.get("network_protocol"))
    # )


    # bytesTransferred = sentbytes + receivedbytes
    # threshold = 10000000 # to be taken from variable
    # # incidrrange=cidr.inRange(destination_ip,"10.0.0.0/8")
    # incidrrange=cidr.inRange(destination_ip, [
    #     "14.141.125.58/30",
    # ])

    # condition2 = (
    #     event.get("destination_port") in destination_ports
    #     or event.get("network_protocol") in application_protocols
    # ) and (
    #     account_name is not None
    #     and account_name not in ["-", "UNKNOWN", ""]
    #     and "$" not in account_name
    # )

    # final_condition = condition1 or condition2
    # if final_condition:


    #     # trigger ONLY when count == 25
    #     if stats.count("abnormal_outside") == 25 and incidrrange and bytesTransferred >= threshold:
    #       stats.resetcount("abnormal_outside")
    #       return 0.75
    #     # otherwise just count, no detection
    # return 0.0


def clusters(event):



    return session.get("anomalies")

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    analysis = session.get("anomalies")[0]
    mean = analysis.get("mean")

    return (
        "Abnormal outbound data transfer detected from source IP "
        + str(event.get("source_ip") or "Unknown")
        + " to external destination "
        + str(event.get("destination_ip") or "Unknown")
        + " outside the approved CIDR range over port "
        + str(event.get("destination_port") or "Unknown")
        + " using protocol "
        + str(event.get("network_protocol") or "Unknown")
        + ". Total bytes transferred: "
        + str(event.get("network_bytes_transferred") or 0)
        + ", which is anomalous compared to the learned baseline mean of "
        + str(mean)
        + " bytes. This may indicate data exfiltration, remote staging, command-and-control traffic, or misuse of outbound trusted services."
    )
    # os_name = event.get("os_name")
    # source_ip = event.get("source_ip")
    # network_protocol = event.get("network_protocol")
    # destination_country = event.get("destination_country")
    # destination_ip = event.get("destination_ip")
    # event_duration = event.get("event_duration")
    # network_bytes_out = event.get("network_bytes_out")
    # network_bytes_in = event.get("network_bytes_in")
    # network_bytes_in = event.get("network_bytes_in")
    # applicationname = event.get("applicationname")
    # application_category = event.get("application_category")
    # application_risk = event.get("application_risk")
    # policy_type = event.get("policy_type")
    # policy_id = event.get("policy_id")
    # context = "A "

    # if os_name:
    #     context += os_name + " device "
    # if source_ip:
    #     context += "(IP: " + source_ip + ") "
    # context += "initiated a secure connection over "

    # if network_protocol:
    #     context += network_protocol + " protocol to a destination in "
    # if destination_country:
    #     context += destination_country + " (IP: "
    # if destination_ip:
    #     context += destination_ip + "), which is outside the range of the organization's CIDR. "

    # if event_duration:
    #     context += "The connection lasted for " + str(event_duration) + " seconds. "
    # if network_bytes_out:
    #     context += "During the connection " + str(network_bytes_out) + " bytes sent from the network and "
    # if network_bytes_in:
    #     context += str(network_bytes_in) + " bytes received on the network, which exceeds the threshold of 10MB. "

    # if applicationname:
    #     context += "The identified application was " + applicationname + ", "
    # if application_category:
    #     context += "categorized under " + application_category + ", "
    # if application_risk:
    #     context += "with a risk level of " + application_risk + ". "

    # context += "This activity triggered a detection log, indicating an abnormal amount of data transmitted over outside the defined CIDR range, in accordance with "

    # if policy_id:
    #     context += " policy ID " + policy_id + "."
    # return context

def criticality():
    return "HIGH"

def tactic():
    return "Exfiltration (TA0010)"

def technique():
    return "Exfiltration Over Alternative Protocol (T1048)"

def artifacts():
    return stats.collect(["source_ip","network_protocol","network_bytes_out","network_bytes_in","destination_ip","destination_country"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
