# Auto-generated by BinaryFlux UI Builder
# FTP Authentication Failure Detection v1.1.0


def init(event):
    """
    Initialize detection
    """
    return "initialization completed"


def window():
    return None


def groupby():
    return ["user_name"]


def investigate():
    return None


def automate():
    return False


def notify():
    return False


def algorithm(event):

    user = (event.get("user_name", "unknown")).replace("\\", "").replace('"', "")

    rediskey = "ftp_fail_" + user

    key = application.get(rediskey)

    if key is True:
        return 0.0

    event_type = (event.get("event_type", "")).upper()

    event_details = (event.get("event_details", "")).lower()

    terminal = (event.get("terminal", "")).lower()

    process_path = (event.get("process_path", "")).lower()

    if (
        event_type in ["USER_AUTH", "USER_LOGIN"] and
        "failed" in event_details and
        terminal == "ftp" and
        "vsftpd" in process_path
    ):

        application.put(rediskey, True, 86400)

        return 0.50

    return 0.0


def clusters(event):

    return session.get("clusterss")


def context(event):

    return (
        "FTP login failed for user "
        + (event.get("user_name", "unknown"))
        + " on "
        + (event.get("host", "unknown"))
        + " using process "
        + (event.get("process_path", "unknown"))
    )


def criticality():
    return "MEDIUM"


def tactic():
    return "Credential Access (TA0006)"


def technique():
    return "Brute Force (T1110)"


def artifacts():

    return stats.collect([
        "host",
        "process_path",
        "event_details",
        "terminal"
    ])


def correlationArtifacts():

    return ["host"]


def entity(event):

    return {
        "derived": False,
        "value": event.get("user_name", "unknown"),
        "type": "email"
    }



#