# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """

    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["source_ip","source_device_name"]

def investigate():
    return "fortigate_network_traffic_anomaly_detection"

def automate():

    # automation: fortigate_network_traffic_anomaly_detection
    return True

def notify():
    return False

def algorithm(event):
    try:
      action = event.get("event_action")
      direction = event.get("network_direction")
      dst_port = str(event.get("destination_port"))
      key = application.get("suspicious_port")

      if key is True:
          return 0.0

      if direction != "inbound":
          return 0.0

      if action!="deny":
          return 0.0
      common_ports = {
          "22", "23", "53", "80", "110", "123",
          "135", "137", "138", "139",
          "143", "443", "445", "993", "995",
          "1433", "1521", "3306", "3389",
          "5432", "5900", "8080", "8443"
      }
      if dst_port in common_ports:
            return 0.0

      dest_port = stats.accumulate(['destination_port'])
      unique_port=len(dest_port.get("destination_port"))
      if unique_port > 20:
        stats.dissipate(['destination_port'])
        lock_acquired = application.putifabsent("suspicious_port", True, 86400)
        if lock_acquired:
          return 0.75
      return 0.0
    except Exception, e:
        print "Error: %s" % e
        return 0.0


def clusters(event):






    return []

def context(event):

    src_ip = event.get('source_ip')
    src_cnt = event.get('source_country')
    dst_cnt = event.get('destination_country')
    dst_ip = event.get('destination_ip')
    src_intf = event.get('source_device_interface')
    dst_intf = event.get('destination_device_interface')
    device = event.get('source_device_name')
    proto = event.get('network_protocol')
    dst_ports = event.get('destination_port')

    # Build the narrative
    message = (
        "The device {device} detected multiple denied connection attempts from {src_ip} ({src_cnt}) "
        "via interface {src_intf} targeting {dst_ip} ({dst_cnt}) on interface {dst_intf} "
        "using protocol {proto} across {dst_ports}. "
        "This activity is consistent with port scanning or network reconnaissance behavior, "
        "as the source host attempted connections to more than 20 ports within a 5 minutes timeframe."
    ).format(
        device=device,
        src_ip=src_ip,
        dst_ip=dst_ip,
        src_intf=src_intf,
        dst_intf=dst_intf,
        proto=proto,
        dst_ports=dst_ports,
        src_cnt=src_cnt,
        dst_cnt=dst_cnt
    )

    return message

def criticality():
    return "HIGH"

def tactic():
    return "Reconnaissance (TA0043)"

def technique():
    return "Active Scanning (T1595)"

def artifacts():
    return stats.collect(["destination_port","source_ip","destination_ip","network_protocol","source_country","destination_country"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
