# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return "30"

def groupby():
    return ["source_account_name"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    if (
        event.get("event_category") == "upload"
        and event.get("threat_name")
        and stats.count("sensitive_file") >= 5
    ):
        return 1.0

    return 0.0


def clusters(event):

    return session.get("clusters")

def context(event):
        return (
        "Proofpoint detected multiple uploads of sensitive files "
        "by user '{0}'. A total of {1} sensitive upload events "
        "were observed within a 30-minute period. The uploaded "
        "files matched DLP classifications such as '{2}'. "
        "Repeated uploads of protected information in a short "
        "timeframe may indicate bulk data transfer, attempted "
        "data exfiltration, or unauthorized sharing of corporate data."
    ).format(
        event.get("source_account_name", "unknown"),
        stats.count("source_account_name"),
        event.get("threat_name", "unknown")
    )

def criticality():
    return "CRITICAL"

def tactic():
    return "Exfiltration (TA0010)"

def technique():
    return "Account Manipulation (T1098)"

def artifacts():
    return stats.collect(["source_account_name","file_name","destination_hostname","threat_name"])

def correlationArtifacts():
    return ["source_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "username"
    }
