# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_execution_and_persistence_activity"

def automate():

    # automation: windows_execution_and_persistence_activity
    return True

def notify():
    return False

def algorithm(event):
    if str(event.get('event_id')) == '7045':
        return 0.75
    return 0.0


def clusters(event):


    return session.get("clusterss")

def context(event):
    return (
        "A new service was created on host " +
        str(event.get('host')) +
        ", which may indicate remote execution."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Lateral Movement (TA0008)"

def technique():
    return "Remote Services (T1021)"

def artifacts():
    return stats.collect(["host","source_account_name","event_id"])

def correlationArtifacts():
    return ["source_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
