# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """

    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_execution_and_persistence_activity"

def automate():

    # automation: windows_execution_and_persistence_activity
    return True

def notify():
    return False

def algorithm(event):
    evt_id = str(event.get("event_id", ""))

    if evt_id != "4698":
        return 0.0

    creator = (event.get("source_account_name") or "").lower()
    task_content = (event.get("task_content") or "").lower()
    # Ignore machine accounts
    if creator.endswith("$"):
        return 0.0

    # Ignore common service/system accounts
    if creator in [
        "system",
        "trustedinstaller",
        "networkservice",
        "localservice"
    ]:
        return 0.0


    # Suspicious indicators
    suspicious_keywords = [
        "powershell",
        "pwsh",
        "cmd.exe",
        "wscript",
        "cscript",
        "mshta",
        "rundll32",
        "regsvr32",
        "bitsadmin",
        "certutil",
        "wmic",
        "-enc",
        "encodedcommand",
        "downloadstring",
        "invoke-expression",
        "iex "
    ]

    suspicious_paths = [
        "\\appdata\\",
        "\\temp\\",
        "\\users\\public\\",
        "\\programdata\\",
        "\\downloads\\"
    ]
    redkey = "suspicious_creation_of_sindows_scheduled_task" + creator
    try:
        key = application.get(redkey)
    except Exception:
        key = None

    if key in (True, "true", "True"):
        return 0.0

    for keyword in suspicious_keywords:
        if keyword in task_content:
            lock_acquired = application.putifabsent(redkey,True,86400)
            if lock_acquired:
              return 0.25

    for path in suspicious_paths:
        if path in task_content:
            lock_acquired = application.putifabsent(redkey,True,86400)
            if lock_acquired:
              return 0.25
    script_extensions = [
        ".ps1",
        ".vbs",
        ".js",
        ".jse",
        ".hta",
        ".bat",
        ".cmd"
    ]

    for ext in script_extensions:
        if ext in task_content:
            return 0.25
    # Generic non-system scheduled task creation
    return 0.0


def clusters(event):











    return session.get("clusters")

def context(event):
    acct = event.get("source_account_name")
    host = event.get("host")
    task = event.get("task_name")
    logon_id = event.get("source_logon_id")
    task_content = (event.get("task_content") or "").lower()

    return (
        "A Windows Scheduled Task '%s' was created on host '%s' "
        "by account '%s' using logon session '%s'. "
        "Task content: '%s'. "
        "This may indicate persistence or automated malicious execution."
    ) % (
        task or "-",
        host or "-",
        acct or "-",
        logon_id or "-",
        task_content[:300]
    )

def criticality():
    return "LOW"

def tactic():
    return "Persistence (TA0003)"

def technique():
    return "Scheduled Task/Job (T1053/005)"

def artifacts():
    return stats.collect(["source_account_name","host","task_content","task_name","source_logon_id","event_id"])

def correlationArtifacts():
    return ["source_account_name","task_name","event_id"]

def huntingQueryTemplate():
    return """SELECT * FROM dictionary
WHERE source_account_name = 
'{{source_account_name}}' and  
event_id = '4698'"""

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }
