# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "15m"

def groupby():
    return ["host"]

def investigate():
    return "linux_authentication___login_activity_monitoring"

def automate():

    # automation: linux_authentication___login_activity_monitoring
    return True

def notify():
    return False

def algorithm(event):
    key = application.get("password_check_fail")

    if key is True:
          return 0.0

    if event.get('event_action') == 'failed' and 'password check failed' in event.get('event_details'):
        if stats.count('pwd_check') == 6:
            stats.resetcount('passwd_check')
            lock_acquired = application.putifabsent("password_check_fail", True, 86400)
            if lock_acquired:
              return 0.75
    return 0.0


def clusters(event):






    return session.get("clusters")

def context(event):
    return (
        "Multiple password check failures detected on host {host} "
        "by process {proc}. More than 5 failures occurred within 15 minutes."
    ).format(
        host=event.get('host'),
        proc=event.get('process_name')
    )

def criticality():
    return "MEDIUM"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Brute Force (T1110)"

def artifacts():
    return stats.collect(["host","process_name","process_id"])

def correlationArtifacts():
    return ["host","process_name"]

def huntingQueryTemplate():
    return """SELECT * FROM dictionary
WHERE host = '{{host}}' AND process_name IN ('unix_chkpwd')"""

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
