TARGET_EVENT_IDS = set([4728, 4732, 4756])
PRIVILEGED_GROUPS = set([
    "Domain Admins",
    "Enterprise Admins",
    "Administrators",
    "Schema Admins",
    "Account Operators",
    "Backup Operators",
    "Server Operators",
    "Print Operators"
])

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_account_privilege_management"

def automate():

    # automation: windows_account_privilege_management
    return True

def notify():
    return False

def algorithm(event):
    event_id = str(event.get('event_id'))

    # User added to security-enabled groups
    if event_id not in [
        '4728',  # global group
        '4732',  # local group
        '4756'   # universal group
    ]:
        return 0.0

    group = str(
        event.get('destination_group_name') or ""
    ).strip()

    if not group:
        return 0.0

    # Detect privileged group additions
    if group not in PRIVILEGED_GROUPS:
        return 0.0

    return 0.75


def clusters(event):



    return session.get("clusterss")

def context(event):
    return (
        "Privileged group membership change detected on host '{host}'. "
        "User '{member}' was added to privileged group '{group}' "
        "by account '{actor}'. Adding users to highly privileged "
        "Active Directory groups may indicate privilege escalation, "
        "unauthorized administrative access, or persistence activity."
    ).format(
        host=event.get('host', 'unknown'),
        member=event.get('member_name', 'unknown'),
        group=event.get('destination_group_name', 'unknown'),
        actor=event.get('source_account_name', 'unknown')
    )

def criticality():
    return "HIGH"

def tactic():
    return "Privilege Escalation (TA0004)"

def technique():
    return "Account Manipulation (T1098)"

def artifacts():
    return stats.collect(["member_name","source_account_name","destination_group_name","host","event_id"])

def correlationArtifacts():
    return ["member_name","destination_group_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("member_name", "unknown"),
        "type": "group"
    }

