# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["destination_account_name"]

def investigate():
    return "windows_authentication_logon_anomalies"

def automate():

    # automation: windows_authentication_logon_anomalies
    return True

def notify():
    return False

def algorithm(event):
    # consider only successful logons (4624)
    evt_id = event.get('event_id')
    source_ip = event.get('source_ip')
    if evt_id != 4624:
        return 0.0

    if not source_ip or source_ip in ['::1', 'UNKNOWN','127.0.0.1','-']:
          return 0.0

    # Filter out machine accounts (like PROINDKOLDC15$)
    acct = (event.get('destination_account_name') or "").strip()
    if acct.endswith('$'):
        return 0.0  # skip machine/service accounts

    # logon type may be in different fields; normalize
    logon_type = int(event.get('logon_type'))

    # only network (3) or remote/interactive over network (10)
    if logon_type not in [3, 10]:
        return 0.0

    try:
      key = application.get("multiple_host_sameaccount_smb_rdp")
    except Exception:
      key = None

    if key in (True, "true", "True"):
        return 0.0

    host_dict = stats.accumulate(['host'])
    unique_host=len(host_dict.get("host"))
    if unique_host > 3:
      stats.dissipate(['host'])
      lock_acquired = application.putifabsent("multiple_host_sameaccount_smb_rdp",True,86400)
      if lock_acquired:
        return 0.75

    return 0.0


def clusters(event):




    return []

def context(event):
    acct = event.get("destination_account_name")
    domain = event.get("destination_account_domain") or "-"
    host = event.get("host")
    src_ip = event.get("source_ip")
    lt = event.get("logon_type")

    # Determine the logon method description dynamically
    if lt == "3":
        logon_desc = "a network logon (SMB, file share, or remote service access)"
    elif lt == "10":
        logon_desc = "a remote desktop (RDP) logon"
    else:
        logon_desc = "an unspecified logon type"

    return (
       "Account '%s\\%s' has authenticated to 3 distinct hosts within the last 15 minutes "
        "using %s from source IP '%s'. Such behavior may indicate credential misuse or lateral movement activity."

    ) % (domain, acct,logon_desc, src_ip)

def criticality():
    return "HIGH"

def tactic():
    return "Lateral Movement (TA0008)"

def technique():
    return "Remote Services (T1021/002)"

def artifacts():
    return stats.collect(["logon_type","host","destination_account_name","source_ip","source_port"])

def correlationArtifacts():
    return ["destination_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("destination_account_name", "unknown"),
        "type": "accountname"
    }
