# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return "30m"

def groupby():
    return ["source_account_name"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    alert_name = str(event.get("alert_name", "")).lower()

    event_category = str(event.get("event_category", "")).lower()
    key = application.get("proofpoint_download_upload_sequence")

    if key is True:
        return 0.0

    if (event_category == "download" and "web file download from corporate cloud" in alert_name):
        stats.count("proofpoint_download_before_upload")

    previous_downloads = int(stats.getcount("proofpoint_download_before_upload") or 0)

    if (event_category == "upload" and ("sensitive data upload" in alert_name or "corporate data exfiltration" in alert_name or "indian pii alert" in alert_name)and previous_downloads >= 1):

        stats.resetcount("proofpoint_download_before_upload")
        lock = application.putifabsent("proofpoint_download_then_sensitive_upload",True,1800)

        if lock:
            return 1.0

    return 0.0


def clusters(event):

    return session.get("clusters")

def context(event):
    return (
        "User '{0}' downloaded corporate information and subsequently "
        "uploaded file '{1}' ({2} bytes) to destination '{3}' "
        "({4}). The upload triggered Proofpoint policy '{5}' and "
        "matched sensitive data classifications '{6}'. This sequence "
        "is consistent with potential data staging and exfiltration "
        "of corporate information and should be reviewed for business "
        "justification and destination legitimacy."
    ).format(
        event.get("source_account_name", "unknown"),
        event.get("file_name", "unknown"),
        event.get("file_size", "unknown"),
        event.get("destination_hostname", "unknown"),
        event.get("url", "unknown"),
        event.get("alert_name", "unknown"),
        event.get("threat_name", "unknown")
    )

def criticality():
    return "CRITICAL"

def tactic():
    return "Exfiltration (TA0010)"

def technique():
    return "Exfiltration Over Web Service (T1567)"

def artifacts():
    return stats.collect(["source_account_name","alert_name","file_name","destination_hostname","url.set"])

def correlationArtifacts():
    return ["source_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "username"
    }
