# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "fortigate_threat_detections_and_preventions"

def automate():

    # automation: fortigate_threat_detections_and_preventions
    return True

def notify():
    return False

def algorithm(event):


    subtype = event.get("log_subtype")
    action = event.get("event_action")

    if (
      not subtype or
      not action
    ):
        return 0.0


    if subtype in ("virus", "ips", "webfilter") and action=="allow":
        return 1.0
    return 0.0


def clusters(event):




    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    # Safely extract relevant FortiGate log values with defaults
    src_ip = event.get('source_ip')
    dst_ip = event.get('destination_ip')
    device = event.get('source_device_name')
    policy_id = event.get('policy_id')
    policy_name = event.get('policy_name')
    action = event.get('event_action')

    # Build the narrative
    message = (
        "The device {device} detected traffic originating from {src_ip} "
        "and targeting {dst_ip} . "
        "The applied firewall policy '{policy_name}' (ID: {policy_id}) took the action '{action}', "
        "allowing the traffic to proceed. "
        "This behavior may indicate a misconfigured or overly permissive security policy, "
    ).format(
        device=device,
        src_ip=src_ip,
        dst_ip=dst_ip,
        src_intf=src_intf,
        dst_intf=dst_intf,
        policy_id=policy_id,
        policy_name=policy_name,
        action=action,
    )

    return message

def criticality():
    return "CRITICAL"

def tactic():
    return "Defense Evasion (TA0005)"

def technique():
    return "Impair Defenses (T1562)"

def artifacts():
    return stats.collect(["policy_id","source_ip","destination_ip","log_subtype","event_action","source_device_name"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "email"
    }
