# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "2m"

def groupby():
    return ["host"]

def investigate():
    return "windows_execution_and_persistence_activity"

def automate():

    # automation: windows_execution_and_persistence_activity
    return True

def notify():
    return False

def algorithm(event):
    evt_id = int(event.get('event_id') or 0)
    if evt_id not in [1, 7, 10]:
        return 0.0

    host = (event.get('host') or '').upper()
    process_name = (event.get('process_name') or '').lower()
    command_line = (event.get('command_line') or '').lower()

    # Only apply to domain controllers (basic heuristic: name contains DC)
    if "DC" not in host and "DOMAIN" not in host:
        return 0.0

    # Suspicious process list (expandable)
    suspicious_processes = [
        'powershell.exe',
        'cmd.exe',
        'rundll32.exe',
        'wmic.exe',
        'wscript.exe',
        'cscript.exe',
        'mshta.exe',
        'regsvr32.exe',
        'psexec.exe'
    ]

    # Check process name or command line content
    for s in suspicious_processes:
        if s in process_name or s in command_line:
            return 1.0

    return 0.0


def clusters(event):



    return session.get("clusterss")

def context(event):
    host = event.get('host')
    proc = event.get('process_name')
    cmd = event.get('command_line')
    return "Suspicious process '%s' executed on Domain Controller %s with command line: %s." % (proc, host, cmd)

def criticality():
    return "CRITICAL"

def tactic():
    return "Execution (TA0002)"

def technique():
    return "Command and Scripting Interpreter (T1059/001)"

def artifacts():
    return stats.collect(["event_id","host","process_name","command_line","source_account_name","source_ip"])

def correlationArtifacts():
    return ["command_line","process_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "hostname"
    }
