# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "10m"

def groupby():
    return ["host","source_account_name","share_name"]

def investigate():
    return "windows_server_session_analyser"

def automate():

    return False

def notify():
    return False

def algorithm(event):
    evt_id = event.get('event_id')
    user = event.get('source_account_name')
    host = event.get('host')
    share = event.get('share_name')


    if evt_id not in [4625, 5140]:
        return 0.0

    is_failed_access = False

    if evt_id == 4625:
        is_failed_access = True
    elif evt_id == 5140:
        result = (event.get('access_result') or event.get('status') or event.get('message') or "").upper()
        if 'DENIED' in result or 'FAILED' in result:
            is_failed_access = True

    if not is_failed_access:
        return 0.0

    key = "failed_share_access"
    stats.count(key)

    if stats.getcount(key) == 6:
        return 0.6

    return 0.0


def clusters(event):

    return session.get("clusters")

def context(event):
    user = event_data.get('source_account_name')
    host = event_data.get('host') 
    share = event_data.get('share_name')

    return "Multiple failed access attempts to share '%s' on host %s by user %s within 10 minutes." % (share, host, user)

def criticality():
    return "MEDIUM"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Brute Force (T1110)"

def artifacts():
    return stats.collect(["event_id","host","source_account_name","share_name","source_ip"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }
