HIGH_VALUE_ACCOUNT_KEYWORDS = [
    "administrator",
    "root",
    "krbtgt",
    "enterprise",
    "domain",
    "backup",
    "oracle",
    "sa",
    "breakglass",
    "emergency"
]
HIGH_VALUE_SAFE_KEYWORDS = [
    "admin",
    "domain",
    "tier0",
    "production",
    "breakglass",
    "emergency"
]

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):

    action = (event.get("event_action") or "").lower()

    if action != "retrieve password":
        return 0.0

    account = (event.get("target_username") or "").lower()
    safe = (event.get("safe_name") or "").lower()

    for keyword in HIGH_VALUE_ACCOUNT_KEYWORDS:
        if keyword in account:
            return 1.0

    for keyword in HIGH_VALUE_SAFE_KEYWORDS:
        if keyword in safe:
            return 1.0

    return 0.0


def clusters(event):







    return session.get("clusters")

def context(event):


    user = event.get("user_name") or "Unknown User"
    account = event.get("target_user") or "Unknown Account"
    safe = event.get("safe_name") or "Unknown Safe"

    return (
        "User '{}' retrieved the password for privileged account '{}' "
        "from Safe '{}'. Retrieval of credentials belonging to sensitive "
        "accounts may indicate privileged access or credential abuse."
    ).format(user, account, safe)

def criticality():
    return "CRITICAL"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Credentials from Password Stores (T1555)"

def artifacts():
    return stats.collect(["target_user","source_ip","destination_ip","applicationname","event_action","user_name"])

def correlationArtifacts():
    return ["target_user","user_name"]

def huntingQueryTemplate():
    return ""

def entity(event):
    return {
        "derived": False,
        "value": event.get("user_name", "unknown"),
        "type": "username"
    }

