# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "1m"

def groupby():
    return ["host","source_account_name"]

def investigate():
    return "windows_security_integrity_and_system_abuse_monitoring"

def automate():

    # automation: windows_security_integrity_and_system_abuse_monitoring
    return True

def notify():
    return False

def algorithm(event):
    actor = event.get('source_account_name')
    evtid = event.get('event_id')

    # Fast check (string compare, no casting)
    if evtid != "1102":
        return 0.0

    if not actor:
        return 0.75

    actor_upper = actor.upper()

    # Use tuple + any() (short-circuits early)
    if any(tok in actor_upper for tok in (
        'SECADMIN', 'SECURITYADMIN', 'SECURITY', 'AUDIT ADMIN'
    )):
        return 0.0

    return 0.75


def clusters(event):




    return session.get("clusterss")

def context(event):
    actor = event.get('source_account_name')
    host = event.get('host')

    return (
        "Audit Log Cleared event (Event ID 1102) detected on host %s by user %s who is not part of the SECADMIN group."
        % (host, actor)
    )

def criticality():
    return "HIGH"

def tactic():
    return "Defense Evasion (TA0005)"

def technique():
    return "Indicator Removal (TA1070)"

def artifacts():
    return stats.collect(["host","source_account_name","process_name","event_id"])

def correlationArtifacts():
    return ["source_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }
