# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Store the session
    """
    return "initialization completed"

def window():
    """
    Defines the time window for aggregating events.
    This is optional. If aggregation is not needed, return None.
    Typical formats: '5m' for 5 minutes, '30s' for 30 seconds, '1h' for 1 hour.
    """
    return "1d"

def groupby():
    """
    Groups events by specific attributes from the SIEM schema.
    Example: ['user_email'], ['ip_address'], etc.
    This affects how statistical functions compute counts/sums.
    """
    return ["host"]

def investigate():
    """
    Defines the automated investigation to run when this detection triggers.
    Example: 'ip_recon', 'malware_scan', etc.
    """
    return "windows_kerberos_and_ticket_activity_monitoring"

def automate():
    """
    Determines whether automated actions should be executed for this detection.
    Returns True if automation is enabled, False otherwise.
    """
    # automation: windows_kerberos_and_ticket_activity_monitoring
    return True

def notify():
    """
    Determines whether an email notification should be sent when this detection triggers.
    Returns True to send notification, False to skip.
    """
    return False

def algorithm(event):

    """
    Core detection logic to compute a risk score.
    stats is an implicit object providing count/sum/avg/min/max/distinct_count over window+group_by.
    Return a float 0.0 to 1.0
    """
    img = (event.get('process_name') or '').lower()
    cmd = (event.get('command_line') or '').lower()
    evt_id = str(event.get('event_id') or '')
    parent = (event.get('parent_process_name') or '').lower()

    ticket_tools = ['mimikatz.exe', 'sekurlsa.exe', 'kerberoast.exe', 'klist.exe', 'powershell.exe']
    ptt_cmds = ['kerberos', 'ticket', 'golden', 'silver', 'ptt', 'tgt', 'svc', 'service', 'krbtgt', '/ticket', 'kerberos::ptt', 'kerberos::golden', 'kerberos::list']
    kerb_event_ids = ['4768', '4769', '4770', '4771', '4624', '4672']

    tool_found = img in ticket_tools
    cmd_found = False
    for keyword in ptt_cmds:
        if keyword in cmd:
            cmd_found = True
            break
    is_tool = tool_found and cmd_found

    is_kerb_event = evt_id in kerb_event_ids
    sus_parent = parent.endswith(('wscript.exe', 'cscript.exe', 'powershell.exe'))

    if is_tool and (is_kerb_event or sus_parent):
        stats.count('ptt_attack')
        c = stats.getcount('ptt_attack')
        if c >= 2:
            return 1.0
        elif c == 1:
            return 0.75
    return 0.0


def clusters(event):
    """
    Store the session
    """
    return "initialization completed"

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    proc = event.get('process_name') or 'Unknown'
    cmd = event.get('command_line') or 'N/A'
    evt = event.get('event_id') or 'N/A'
    par = event.get('parent_process_name') or 'Unknown'

    return (
        "A suspected Pass-the-Ticket attack (T1550.003) has been detected involving credential access tactics. "
        "Process '{0}' spawned by '{1}' executed suspicious command: '{2}'. "
        "Event ID {3} indicates Kerberos authentication activity. "
        "This is categorized under Credential Access (TA0006). "
        "Investigate immediately to verify if this is legitimate service account activity."
    ).format(proc, par, cmd, evt)

def criticality():
    """
    Defines the criticality level of the detection.
    Options: 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'.
    """
    return "CRITICAL"

def tactic():
    """
    Maps this detection to a MITRE ATT&CK tactic.
    Example: 'Persistence (TA0003)', 'Credential Access (TA0006)', etc.
    """
    return "Credential Access (TA0006)"

def technique():
    """
    Maps this detection to a MITRE ATT&CK technique.
    Example: 'Account Manipulation (T1098)', 'Phishing (T1566)', etc.
    """
    return "Pass the Ticket (T1550/003)"

def artifacts():
    """
    Collects unique values of specified attributes across the event window.
    Uses stats.collect() to gather these artifacts.
    """
    return stats.collect(["event_id","process_name"])

def correlation():
    """
    Groups events by specific attributes from the SIEM schema.
    Example: ['user_email'], ['ip_address'], etc.
    This affects how statistical functions compute counts/sums.
    """
    return []

def entity(event):
    """
    Identifies the primary entity related to this detection.
    Can be directly from event attribute or derived.
    """
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "email"
    }
