# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["user_email"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    evt_id = str(event.get("event_id"))

    # 1. Look for claims mapping changes
    if evt_id == "501":
        # Claims provider configuration reload/modifications
        return 0.65

    # 2. Command lines modifying claims provider rules
    elif evt_id == "4688":
        cmd = (event.get("command_line") or "").lower()

        # Adding claims rules or registering custom providers
        persistence_indicators = [
            "claimrule", "claimruleset", "add-adfsclaimsprovidertrust",
            "new-adfsclaimsprovidertrust", "set-adfsclaimsprovidertrust",
            "update-adfsclaimsprovidertrust"
        ]

        for pi in persistence_indicators:
            if pi in cmd:
                return 0.85  # High risk: configuring claim maps for persistence

    return 0.0


def clusters(event):

    return session.get("clusters")

def context(event):
    host = event.get("host")
    user = event.get("source_account_name")
    evt_id = event.get("event_id")
    cmd = event.get("command_line") or "-"

    if evt_id == "501":
        return (
            "AD FS claims mapping change (Event 501) logged on host '%s' by user '%s'. "
            "This configuration change may affect Claims Provider trust rules."
        ) % (host, user)
    else:
        return (
            "AD FS claims provider persistence command executed on host '%s' by user '%s' "
            "with command line: '%s'. This indicates potential modification of trust rules or claim maps."
        ) % (host, user, cmd)

def criticality():
    return "HIGH"

def tactic():
    return "Persistence (TA0003)"

def technique():
    return "Account Manipulation (T1098)"

def artifacts():
    return stats.collect(["event_id","host","source_account_name","command_line"])

def correlationArtifacts():
    return ["source_account_name"]

def huntingQueryTemplate():
    return ""

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
