WHITELIST_ACCOUNTS = [
    "nt authority\\system","nt authority\\network service","nt authority\\local service",
    "system","localservice","networkservice",
    "backupsvc","svc_backup","veeam","veeamagent","commvault","veritas","arcserve",
    "dpmbackup","rubrik","cohesity",
    "crowdstrike","falcon","carbonblack","sentinelone","defender","sophos",
    "mcafee","trendmicro","symantec","eset","cybereason",
    "sccm","wsus","intune","pdqdeploy","landesk","altiris","tanium",
    "chef","puppet","ansible","jamf",
    "onedrive","sharepoint","dropbox","googledrive","nextcloud","owncloud",
    "synology","qnap",
    "svc_filecopy","svc_batch","svc_scheduledtask","svc_filesync",
    "svc_replication","svc_dbbackup","svc_maintenance","svc_monitor",
    "svc_orchestrator",
    "vmtools","vmware","hyperv","vcenter","svc_esxi","svc_vmbackup",
    "azureadconnect","adconnect","azurebackup","gmsa","svc_azureagent",
    "svc_msol","svc_adfs"
]
WHITELIST_LOWER = [w.lower() for w in WHITELIST_ACCOUNTS]

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):


    # Ensure it's Event ID 4672 (Special Logon)
    if event.get('event_id') != "4660":
        return 0.0  # Ignore other events

    # Extract key fields
    user = event.get("source_account_name", "").lower()
    key = application.get("windows_obejct_delete_per_account"+str(user))

    # If key is already set, always return 0.0
    if key is True:
        return 0.0


    if not user or user in ["-", "unknown"]:
        return 0.0

    if _is_whitelisted_account(user):
        return 0.0

    # Only file server activity
    if not (event.get("share_name") or event.get("share_path")):
        return 0.0

    application.put("windows_obejct_delete_per_account"+str(user), True, 86400)
    return 0.5


def clusters(event):

    return session.get("clusterss")

def context(event):
    user = event.get("source_account_name") or "unknown"
    host = event.get("host") or "unknown"
    process = event.get("process_name") or "unknown"

    return (
        "Object deletion activity detected for source account '" + user + "'. "
        "The deletion event (Event ID 4660) was generated on host '" + host + 
        "' by process '" + process + "'. "
        "This record provides visibility into deletion behavior associated with this account "
        "and is intended for monitoring, baselining, and correlation with other security events "
        "to identify unusual or potentially unauthorized activity."
    )

def criticality():
    return "MEDIUM"

def tactic():
    return "Impact (TA0040)"

def technique():
    return "Data Destruction (T1485)"

def artifacts():
    return stats.collect(["source_account_name","process_name","host"])

def correlationArtifacts():
    return ["source_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }


def _is_whitelisted_account(account):
    for w in WHITELIST_LOWER:
        if w in account:
            return True
    return False