# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """

    return "initialization completed"

def window():
    return "1h"

def groupby():
    return ["user_name"]

def investigate():
    return "fortigate_authentication___access_security"

def automate():

    # automation: fortigate_authentication___access_security
    return True

def notify():
    return False

def algorithm(event):

    action = str(event.get("event_action") or "").lower()
    alert = str(event.get("event") or "").lower()
    src_ip = str(event.get("source_ip") or "")
    key = application.get("FSSO_login")

    if key is True:
        return 0.0

    if not src_ip:
        return 0.0

    if "fsso" not in action:
        return 0.0

    if "authentication status" not in alert:
        return 0.0


    ips = stats.accumulate(["source_ip"])
    unique_ips = len(ips.get("source_ip"))

    if unique_ips > 5:
        stats.dissipate(["source_ip"])
        lock_acquired = application.putifabsent("FSSO_login", True, 86400)
        if lock_acquired:
          return 0.75

    return 0.0


def clusters(event):





    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    return (
        "User "
        + str(event.get("user_name") or "Unknown")
        + " authenticated through FSSO from multiple distinct source IP addresses within one hour. "
        + "Current observed source IP: "
        + str(event.get("source_ip") or "Unknown")
        + ". This may indicate credential sharing, roaming behavior, proxy/NAT changes, or possible account misuse."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Valid Accounts (T1078)"

def artifacts():
    return stats.collect(["user_name","source_ip","event_action","source_device_name"])

def correlationArtifacts():
    return ["user_name","event_action"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
