# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "10m"

def groupby():
    return ["source_ip"]

def investigate():
    return "windows_authentication_logon_anomalies"

def automate():

    # automation: windows_authentication_logon_anomalies
    return True

def notify():
    return False

def algorithm(event):
    if event.get('event_id') == "4624" and event.get('logon_type') == "10":
        if stats.count('excessive_rdp_logins') > 5:
            stats.resetcount('excessive_rdp_logins')
            return 0.75
    return 0.0


def clusters(event):



    return session.get("clusterss")

def context(event):
    src_ip = event.get('source_ip', '-')
    dest_user = event.get('destination_account_name', '-')
    domain = event.get('destination_account_domain', '-')
    host = event.get('host', '-')
    process = event.get('process_name', '-')
    src_port = event.get('source_port', '-')

    return (
        "Multiple successful RDP (Logon Type 10) logons were detected within a 10-minute window. "
        "Source IP " + src_ip + " initiated more than five successful logons "
        "to host " + host + " targeting account " + dest_user + " "
        "under domain " + domain + " using process " + process + " "
        "on source port " + src_port + ". "
        "This behavior may indicate lateral movement or unauthorized remote access."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Lateral Movement (TA0008)"

def technique():
    return "Remote Services (T1021/001)"

def artifacts():
    return stats.collect(["source_ip","destination_account_name","process_name","destination_account_domain","host","source_port"])

def correlationArtifacts():
    return ["destination_account_name","process_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
