
# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "fortigate_system_integrity_monitoring"

def automate():

    # automation: fortigate_system_integrity_monitoring
    return True

def notify():
    return False

def algorithm(event):
    dev = event.get("source_device_name")
    key = "login_disable:" + str(dev)
    if application.get(key) is True:
        return 0.0

    if (not event.get('event_alert')):
        return 0.0

    if (
        event.get('event_action') == 'login' and 
        event.get('event_alert') == 'exceed_limit' and 
        'Login disabled from' in str(event.get('event_details'))):
            application.put(key, True, 86400)
            return 0.75
    return 0.0


def clusters(event):









    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    return str(event.get('event_details')) + " due to " + str(event.get('event_alert'))

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Brute Force (T1110)"

def artifacts():
    return stats.collect(["event_severity","event_action","event_alert","source_device_name"])

def correlationArtifacts():
    return ["source_device_name"]

def huntingQueryTemplate():
    return """SELECT * FROM dictionary
WHERE source_device_name = '{{source_device_name}}' AND event_action IN ('login', 'Login')"""

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_device_name", "unknown"),
        "type": "host"
    }


def correlation():
    """
    Groups events by specific attributes from the SIEM schema.
    Example: ['user_email'], ['ip_address'], etc.
    This affects how statistical functions compute counts/sums.
    """
    return ["event_alert"]