# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "10m"

def groupby():
    return ["source_ip","source_device_name"]

def investigate():
    return None

def automate():

    return True

def notify():
    return False

def algorithm(event):

    type = event.get('log_type')
    subtype = event.get('log_subtype')
    message = event.get('event_details')
    action = event.get('event_action')

    # Trigger if type matches and destination IP is malicious
    if type == 'log' and subtype == 'wan' and action == 'system' and 'login failed'in message:
      if stats.count("login_fail") == 6:
        stats.resetcount("login_fail")
        return 0.75
    return 0.0


def clusters(event):



    return session.get("clusterss")

def context(event):
    # Safely extract relevant FortiGate log values with defaults
    src_ip = event_data.get('source_ip') 
    src_port = event_data.get('source_port') 
    dst_ip = event_data.get('destination_ip')
    dst_port = event_data.get('destination_port') 
    device = event_data.get('source_device_name')
    country = event_data.get('source_country') 
    interface = event_data.get('destination_interface') 

    # Build the narrative
    message = (
        "The FortiGate firewall device {device} recorded multiple failed administrative login attempts in a 10 minutes windows "
        "from {src_ip}:{src_port} (originating from {country}) targeting {dst_ip}:{dst_port}. "
        "The attempts used the interface {interface}. "
        "This pattern suggests a possible brute-force or credential guessing attempt against the "
        "firewall's management interface. Continued failures from the same source may indicate "
        "malicious probing or an attempt to gain unauthorized administrative access."
    ).format(
        device=device,
        src_ip=src_ip,
        src_port=src_port,
        dst_ip=dst_ip,
        dst_port=dst_port,
        interface=interface,
        country=country
    )

    return message

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Brute Force (T1110)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","source_device_name","log_type","log_subtype","event_action"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
