RC4_ENCRYPTION = ["0x17", "23"]

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """

    return "initialization completed"

def window():
    return "10m"

def groupby():
    return ["source_account_name","source_ip"]

def investigate():
    return "windows_kerberos_and_ticket_activity_monitoring"

def automate():

    # automation: windows_kerberos_and_ticket_activity_monitoring
    return True

def notify():
    return False

def algorithm(event):
    # Kerberos Service Ticket Request
    if str(event.get('event_id')) != '4769':
        return 0.0

    encryption = str(
        event.get("ticket_encryption_type", "")
    ).lower()

    service_name = str(
        event.get("service_name", "")
    ).lower()

    # Ignore machine accounts
    if service_name.endswith("$"):
        return 0.0

    # RC4 tickets are highly suspicious
    if encryption in RC4_ENCRYPTION:
      if stats.count("windows_kerberoast_rc4_requests") > 5:
        stats.resetcount("windows_kerberoast_rc4_requests")
        return 0.75

    return 0.0


def clusters(event):




    return session.get("clusterss")

def context(event):
    return (
        "Multiple Kerberos service ticket requests using RC4 encryption "
        "detected from account " +
        str(event.get('source_account_name')) +
        " targeting service " +
        str(event.get('service_name')) +
        ". This may indicate Kerberoasting activity."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Kerberoasting (T1558.003)"

def artifacts():
    return stats.collect(["source_account_name","source_ip","event_id","service_name","ticket_encryption_type"])

def correlationArtifacts():
    return ["source_account_name","ticket_encryption_type"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }

