# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Store the session
    """
    return "initialization completed"

def window():
    """
    Defines the time window for aggregating events.
    This is optional. If aggregation is not needed, return None.
    Typical formats: '5m' for 5 minutes, '30s' for 30 seconds, '1h' for 1 hour.
    """
    return "10m"

def groupby():
    # DC-based logs → group by user + IP
    return ["source_account_name", "source_ip"]

def investigate():
    """
    Defines the automated investigation to run when this detection triggers.
    Example: 'ip_recon', 'malware_scan', etc.
    """
    return "windows_authentication_logon_anomalies"

def automate():
    """
    Determines whether automated actions should be executed for this detection.
    Returns True if automation is enabled, False otherwise.
    """
    # automation: windows_authentication_logon_anomalies
    return True

def notify():
    """
    Determines whether an email notification should be sent when this detection triggers.
    Returns True to send notification, False to skip.
    """
    return False

def algorithm(event):

    event_id = str(event.get("event_id") or "")
    event_type = (event.get("event_type") or "").upper()
    logon_type = str(event.get("logon_type") or "")
    user = event.get("source_account_name") or ""

    # -----------------------------
    # FILTER NOISE
    # -----------------------------
    if user.endswith("$"):
        return 0.0

    if logon_type not in ["3", "10"]:
        return 0.0

    # -----------------------------
    # COUNT EVENTS
    # -----------------------------
    if event_id == "4625" or "FAILURE" in event_type:
        stats.count("failures")

    if event_id == "4624" or "SUCCESS" in event_type:
        stats.count("successes")

    failures = int(stats.getcount("failures") or 0)
    successes = int(stats.getcount("successes") or 0)

    # -----------------------------
    # DETECTION
    # -----------------------------
    if failures >= 5 and successes >= 1:
        return 0.9   # ✅ single fixed score

    return 0.0

def clusters(event):
    """
    Store the session
    """
    return "initialization completed"

def context(event):

    user = event.get("source_account_name") or "unknown"
    ip = event.get("source_ip") or "unknown"
    host = event.get("host") or "unknown"
    auth = event.get("auth_package") or "unknown"

    return (
        "Multiple failed logins followed by success detected for user "
        + user +
        " from IP " + ip +
        " on host " + host +
        " using " + auth +
        " authentication. Possible brute force attack."
    )

def criticality():
    """
    Defines the criticality level of the detection.
    Options: 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'.
    """
    return "HIGH"

def tactic():
    """
    Maps this detection to a MITRE ATT&CK tactic.
    Example: 'Persistence (TA0003)', 'Credential Access (TA0006)', etc.
    """
    return "Credential Access (TA0006)"

def technique():
    """
    Maps this detection to a MITRE ATT&CK technique.
    Example: 'Account Manipulation (T1098)', 'Phishing (T1566)', etc.
    """
    return "Brute Force (T1110)"

def artifacts():
    """
    Collects unique values of specified attributes across the event window.
    Uses stats.collect() to gather these artifacts.
    """
    return stats.collect(["event_id",
        "event_type",
        "host",
        "source_account_name",
        "source_ip",
        "logon_type",
        "auth_package",
        "elevated_token",
        "impersonation_level"])

def correlation():
    """
    Groups events by specific attributes from the SIEM schema.
    Example: ['user_email'], ['ip_address'], etc.
    This affects how statistical functions compute counts/sums.
    """
    return []

def entity(event):
    """
    Identifies the primary entity related to this detection.
    Can be directly from event attribute or derived.
    """
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }
