# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return ["host"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    proc = (event.get('process_name') or '').lower()
    parent = (event.get('parent_process') or '').lower()
    cmd = (event.get('command_line') or '').lower()

    key = application.get("suspicious_parent_child")

    # Prevent duplicate alerts
    if key is True:
        return 0.0

    if not proc or not parent:
        return 0.0

    suspicious_parents = ['powershell', 'cmd', 'wscript', 'cscript']
    target_processes = ['svchost', 'explorer', 'lsass']

    # Flexible matching
    if not any(p in parent for p in suspicious_parents):
        return 0.0

    if not any(t in proc for t in target_processes):
        return 0.0

    # Strengthen with command-line indicators
    if cmd:
        if any(x in cmd for x in ['-enc', 'http', 'base64']):
            application.put("suspicious_parent_child", True, 3600)
            return 0.75

    # Still suspicious even without cmd
    application.put("suspicious_parent_child", True, 3600)
    return 0.75


def clusters(event):

    return session.get("clusterss")

def context(event):
    proc = event_data.get('process_name')
    parent = event_data.get('parent_process')
    host = event_data.get('host')
    user = event_data.get('user_name')

    context = "Suspicious process relationship detected "

    if parent:
        context += "where parent process " + str(parent) + " "

    if proc:
        context += "spawned child process " + str(proc) + " "

    if user:
        context += "under user " + str(user) + " "

    if host:
        context += "on host " + str(host) + " "

    context += "This behavior may indicate misuse of scripting engines or abnormal execution chains."

    return context

def criticality():
    return "HIGH"

def tactic():
    return "Execution (TA0002)"

def technique():
    return "Command and Scripting Interpreter (T1059)"

def artifacts():
    return stats.collect(["process_name","parent_process","command_line","user_name","host"])

def correlationArtifacts():
    return ["host"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
