# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "fortigate_system_integrity_monitoring"

def automate():

    return True

def notify():
    return False

def algorithm(event):


    subtype = (event.get("log_subtype") or "").lower()
    msg = (event.get("event_details") or "").lower()
    srcintf = (event.get("source_device_interface") or "").lower()
    dstintf = (event.get("destination_device_interface") or "").lower()
    action = (event.get("event_action") or "").lower()

    if not msg:
        return 0.0

    if subtype != "system":
        return 0.0

    if "policy" not in msg:
        return 0.0

    changed = any(word in msg for word in [
        "create", "created", "update", "updated",
        "modify", "modified", "change", "changed"
    ])

    if "allow all" in msg:
        return 1.0

    if changed and srcintf == "any" and dstintf == "any" and action in ["accept", "allow", "permit"]:
        return 1.0

    return 0.0


def clusters(event):





    """
    Store the session
    """
    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    # Safely extract relevant FortiGate log values with defaults
    policy_id = eventevent.get('policy_id')
    policy_name = event.get('policy_name')
    action = event.get('event_action') 
    src_intf = event.get('source_device_interface')
    dst_intf = event.get('destination_device_interface')
    device = event.get('source_device_name')
    # Build the narrative
    message = (
        "At device {device} reported a configuration change "
        "The system log indicates a firewall policy modification: '{policy_name}' (ID: {policy_id}). "
        "The rule allows traffic from {src_intf} to {dst_intf} with the action set to '{action}'. "
        "This configuration effectively permits unrestricted network access, which may represent "
        "a misconfiguration or deliberate tampering with security controls. "
        "Such an 'allow-all' policy can expose the network to unauthorized access or lateral movement."
    ).format(
        device=device,
        admin_user=admin_user,
        policy_name=policy_name,
        policy_id=policy_id,
        src_intf=src_intf,
        dst_intf=dst_intf,
        action=action,
        msg=msg
    )
    return message

def criticality():
    return "CRITICAL"

def tactic():
    return "Defense Evasion (TA0005)"

def technique():
    return "Impair Defenses (T1562)"

def artifacts():
    return stats.collect(["policy_id","source_device_interface","destination_device_interface","log_subtype","source_ip","destination_ip","source_device_name"])

def correlationArtifacts():
    return ["source_device_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
