# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return ["host"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    path = (event.get('file_path') or '').lower()
    proc = (event.get('process_name') or '').lower()
    cmd = (event.get('command_line') or '').lower()

    key = application.get("suspicious_dll_exec")

    # Prevent duplicate alerts
    if key is True:
        return 0.0

    if not path:
        return 0.0

    # Must be DLL
    if not path.endswith('.dll'):
        return 0.0

    # Suspicious directories
    suspicious_paths = ['\\temp\\', '/temp/', '\\appdata\\', '/appdata/']

    if not any(p in path for p in suspicious_paths):
        return 0.0

    # Strengthen with suspicious processes
    suspicious_procs = ['rundll32', 'powershell', 'regsvr32']

    if proc and any(p in proc for p in suspicious_procs):
        application.put("suspicious_dll_exec", True, 3600)
        return 0.75

    # Or suspicious command-line usage
    if cmd and any(x in cmd for x in ['rundll32', 'regsvr32']):
        application.put("suspicious_dll_exec", True, 3600)
        return 0.75

    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    path = event_data.get('file_path')
    proc = event_data.get('process_name')
    host = event_data.get('host')
    user = event_data.get('user_name')

    context = "Suspicious DLL execution detected "

    if path:
        context += "from path " + str(path) + " "

    if proc:
        context += "via process " + str(proc) + " "

    if user:
        context += "under user " + str(user) + " "

    if host:
        context += "on host " + str(host) + " "

    context += "This may indicate execution of a malicious DLL from a non-standard location."

    return context

def criticality():
    return "HIGH"

def tactic():
    return "Defense Evasion (TA0005)"

def technique():
    return "Signed Binary Proxy Execution (T1218)"

def artifacts():
    return stats.collect(["file_path","process_name","command_line","user_name","host"])

def correlationArtifacts():
    return ["host"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
