# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_kerberos_and_ticket_activity_monitoring"

def automate():

    # automation: windows_kerberos_and_ticket_activity_monitoring
    return True

def notify():
    return False

def algorithm(event):
    if str(event.get('event_id')) == '4624':
        if event.get('logon_type') == '3' and not event.get('source_ip'):
            return 0.75
    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    return (
        "Suspicious Kerberos service ticket usage detected for user " +
        str(event.get('source_account_name')) +
        " which may indicate Silver Ticket abuse."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Persistence (TA0003)"

def technique():
    return "Silver Ticket (T1558.002)"

def artifacts():
    return stats.collect(["source_account_name","source_ip","event_id"])

def correlationArtifacts():
    return ["source_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "email"
    }
