# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["destination_account_name","source_ip"]

def investigate():
    return "windows_authentication_logon_anomalies"

def automate():

    # automation: windows_authentication_logon_anomalies
    return True

def notify():
    return False

def algorithm(event):

    evt_id = str(event.get("event_id") or "")
    if evt_id != "4625":  # Only failed logons
        return 0.0

    src_ip = event.get("source_ip")
    acct = (event.get("destination_account_name") or "").strip()
    logon_type = event.get("logon_type")
    status = (event.get("sub_status") or "").lower()

    # ignore noise
    if not src_ip or src_ip in ["-", "UNKNOWN", "127.0.0.1", "::1"]:
        return 0.0

    if not acct or acct.endswith("$"):
        return 0.0

    #  focus on meaningful logons
    if logon_type not in ["2", "3", "10"]:
        return 0.0


    if  stats.count("failed_logons_per_source_account") >5 :
        stats.resetcount("failed_logons_per_source_account")
        return 0.75  # fixed high-confidence score

    return 0.0


def clusters(event):






    return session.get("clusterss")

def context(event):
    src_ip = event.get("source_ip") or "unknown source"
    acct = event.get("destination_account_name") or "unknown account"
    host = event.get("host") or "unknown host"
    process = event.get("process_name") or "unknown process"
    logon_type = event.get("logon_type") or "unknown"
    status = (event.get("sub_status") or "").lower()

    # failure interpretation
    if status == "0xc000006a":
        reason = "incorrect password attempts"
    elif status == "0xc0000064":
        reason = "invalid or non-existent usernames"
    else:
        reason = "authentication failures"

    return (
        "Multiple failed logon attempts detected from source IP "
        + str(src_ip)
        + " targeting account "
        + str(acct)
        + " on host "
        + str(host)
        + ". "
        "Repeated "
        + reason
        + " were observed within a short time window using logon type "
        + str(logon_type)
        + ". "
        "The activity is associated with process "
        + str(process)
        + ", indicating a likely brute-force or password guessing attack."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Brute Force (T1110)"

def artifacts():
    return stats.collect(["event_id","event_type","host","source_ip","source_port","destination_account_name","logon_type","process_name"])

def correlationArtifacts():
    return ["destination_account_name","source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("destination_account_name", "unknown"),
        "type": "accountname"
    }
