
# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    analysis = stats.zanomaly("network_bytes_out")
    session.set("anomalies", [analysis])
    return "Initialized zanomaly detection"

def window():
    return "10m"

def groupby():
    return ["source_ip"]

def investigate():
    return "fortigate_outbound_threat_monitoring"

def automate():

    # automation: fortigate_outbound_threat_monitoring
    return True

def notify():
    return False

def algorithm(event):

    protocol = (event.get("network_protocol") or "").lower()
    port = str(event.get("destination_port") or "")
    action = (event.get("event_action") or "").lower()
    src = event.get("source_ip")
    dst = event.get("destination_ip")

    key = "protocol_tunneling:" + str(src)

    if action not in ["allow", "accept", "permit"]:
        return 0.0

    if not protocol or not port or not src or not dst:
        return 0.0

    if application.get(key) is True:
        return 0.0

    if _is_internal_ip(dst):
        return 0.0

    standard_ports = {
        "http": ["80", "8080", "8000"],
        "https": ["443", "8443"],
        "dns": ["53"],
        "ssh": ["22", "2222"],
        "ftp": ["21"],
        "rdp": ["3389"]
    }

    suspicious = False

    # Standard protocol on unusual port
    if protocol in standard_ports:
        if port not in standard_ports[protocol]:
            suspicious = True

    # DNS / ICMP volume anomaly instead of static threshold
    if protocol in ["dns", "icmp"]:
        analysis = session.get("anomalies")[0]
        anomaly = analysis.get("anomaly")

        if anomaly == 1:
            suspicious = True

    if suspicious:
        application.put(key, True, 86400)
        return 0.75

    return 0.0


def clusters(event):


    return session.get("anomalies")

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """

    context = (
        "Suspicious protocol usage detected from source IP "
        + (event.get("source_ip"))
        + " communicating over protocol "
        + (event.get("network_protocol"))
        + " on port "
        + (event.get("destination_port"))
    )

    if (event.get("network_protocol") or "").lower() in ["dns", "icmp"]:
        analysis = session.get("anomalies")[0]
        mean = analysis.get("mean")
        context += (
            ". Outbound byte volume is anomalous compared to the normal baseline mean of "
            + str(mean)
            + " bytes."
        )

    context += " This behavior may indicate protocol tunneling or attempts to bypass security controls."

    return context

def criticality():
    return "HIGH"

def tactic():
    return "Defense Evasion (TA0005)"

def technique():
    return "Protocol Tunneling (T1572)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","destination_port","network_protocol","network_bytes_out","url"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }


def _is_internal_ip(ip):
    if not ip:
        return False
    return ip.startswith('10.') or ip.startswith('192.168.') or ip.startswith('172.')