# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["source_ip"]

def investigate():
    return "fortigate_authentication___access_security"

def automate():

    # automation: fortigate_authentication___access_security
    return True

def notify():
    return False

def algorithm(event):

    message = (event.get("event") or "").lower()
    src_ip = event.get("source_ip")
    key = application.get("brute_force")

    if key is True:
        return 0.0

    if not message or not src_ip:
        return 0.0

    # Failed login indicators
    if (
        "login failed" in message or
        "authentication failed" in message or
        "invalid user" in message
    ):

        count = stats.count("failed_login_attempts")

        if count > 5:
            stats.resetcount("failed_login_attempts")
            lock_acquired = application.putifabsent("brute_force", True, 86400)
            if lock_acquired:
              return 0.75

    return 0.0


def clusters(event):



    return session.get("clusterss")

def context(event):

    return (
        "Multiple failed login attempts detected from user" + str(event_data.get("user_name")) + " with source IP "
        + str(event_data.get("source_ip")) + " with action " + str(event_data.get("event_action")) +
        " within a short time window. This pattern indicates a possible brute-force attack "
        "attempting to gain unauthorized access."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Brute Force (T1110)"

def artifacts():
    return stats.collect(["source_ip","event_details","destination_ip","destination_port","event_action","user_name"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
