# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return "10m"

def groupby():
    return ["source_ip"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    event_id = str(event.get("event_id"))
    source_ip = event.get("source_ip")
    proxy_server = event.get("proxy_server")

    if not source_ip or source_ip == "UNKNOWN":
        return 0.0

    suspicious = False

    if event_id == "1203":
        if proxy_server and proxy_server not in ("-", "N/A"):
            suspicious = True

    elif event_id == "403":
        url_path = (event.get("url_path") or "").lower()
        if (
            proxy_server
            and proxy_server not in ("-", "N/A")
            and ("adfs/ls" in url_path or "usernamemixed" in url_path)
        ):
            suspicious = True

    if not suspicious:
        return 0.0

    if stats.count("adfs_proxy_activity") >= 10:
        return 0.75

    return 0.0


def clusters(event):

    return session.get("clusters")

def context(event):
    if str(event.get("event_id")) == "1203":
        return (
            "Detected multiple failed AD FS credential validation attempts from source IP '%s' "
            "through proxy server '%s'. Total suspicious proxy authentication events: %d."
        ) % (
            event.get("source_ip", "-"),
            event.get("proxy_server", "-"),
            stats.count("adfs_proxy_activity"),
        )

    return (
        "Detected repeated requests to AD FS authentication endpoints from source IP '%s' "
        "through proxy server '%s'. Total suspicious proxy authentication events: %d."
    ) % (
        event.get("source_ip", "-"),
        event.get("proxy_server", "-"),
        stats.count("adfs_proxy_activity"),
    )

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Brute Force (T1110/003)"

def artifacts():
    return stats.collect(["source_account_name","destination_account_name","event_id","host","source_ip"])

def correlationArtifacts():
    return ["source_ip"]

def huntingQueryTemplate():
    return ""

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
