# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    evt_id = str(event.get("event_id"))

    # 1. Configuration modification events
    if evt_id in ["500", "501"]:
        # Changes are sensitive; if it contains modifying indicators or if we alert on configuration modifications
        return 0.75

    # 2. PowerShell modifications of trust configuration
    elif evt_id == "4688":
        cmd = (event.get("command_line") or "").lower()
        manipulation_cmdlets = [
            "set-adfsrelyingpartytrust", "add-adfsrelyingpartytrust",
            "set-adfsclaimsprovidertrust", "add-adfsclaimsprovidertrust",
            "update-adfsrelyingpartytrust", "remove-adfsrelyingpartytrust",
            "remove-adfsclaimsprovidertrust"
        ]
        for mc in manipulation_cmdlets:
            if mc in cmd:
                return 0.75  # High risk federation trust change command

    return 0.0


def clusters(event):

    return session.get("clusters")

def context(event):
    host = event.get("host")
    user = event.get("source_account_name")
    evt_id = event.get("event_id")
    cmd = event.get("command_line") or "-"

    if evt_id in ["500", "501"]:
        return (
            "AD FS Federation configuration modification (Event %s) logged on host '%s' by user '%s'. "
            "This configuration change may affect Relying Party or Claims Provider trust relationships."
        ) % (evt_id, host, user)
    else:
        return (
            "AD FS Federation configuration command executed on host '%s' by user '%s' "
            "with command line: '%s'. This indicates potential modification of federation trust parameters."
        ) % (host, user, cmd)

def criticality():
    return "MEDIUM"

def tactic():
    return "Persistence (TA0003)"

def technique():
    return "Modify Authentication Process (T1556/006)"

def artifacts():
    return stats.collect(["event_id","host","source_account_name","command_line"])

def correlationArtifacts():
    return ["source_account_name"]

def huntingQueryTemplate():
    return ""

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
