HIGH_RISK_COUNTRIES = ["RU", "CN", "KP", "IR"]

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return True

def notify():
    return False

def algorithm(event):
    country = event.get("destination_country")
    src = event.get("source_ip")

    # Only consider outbound traffic from internal/private IPs
    if src and (src.startswith("10.") or src.startswith("192.168.") or src.startswith("172.")):
        if country in HIGH_RISK_COUNTRIES:
            return 0.5

    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    src = event.get("source_ip")
    dst = event.get("destination_ip")
    country = event.get("destination_country")
    app = event.get("applicationname")
    zone_src = event.get("source_zone")
    zone_dst = event.get("destination_zone")

    return (
        "Internal host '%s' from zone '%s' initiated outbound communication to destination '%s' "
        "located in country '%s' via application '%s' (zone '%s'). "
        "This behavior indicates potential suspicious external communication, often associated with "
        "command-and-control activity, unauthorized access, or early-stage compromise."
    ) % (src, zone_src, dst, country, app, zone_dst)

def criticality():
    return "MEDIUM"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Application Layer Protocol (T1071)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","destination_country","applicationname","source_zone","destination_zone"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }

