# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):


    action = (event.get("event_action") or "").strip().lower()

    if action == "update safe member":
        return 1.0

    return 0.0


def clusters(event):




    return session.get("clusters")

def context(event):
    user = event.get("user_name") or "Unknown User"
    safe = event.get("safe_name") or "Unknown Safe"

    return (
        "User '{}' modified permissions for a member of CyberArk Safe '{}'. "
        "Changes to Safe permissions may grant or revoke access to privileged "
        "credentials and should be reviewed for authorized administrative activity."
    ).format(user, safe)

def criticality():
    return "CRITICAL"

def tactic():
    return "Persistence (TA0003)"

def technique():
    return "Account Manipulation (T1098)"

def artifacts():
    return stats.collect(["user_name","source_ip","source_hostname","applicationname","event_action"])

def correlationArtifacts():
    return ["user_name"]

def huntingQueryTemplate():
    return ""

def entity(event):
    return {
        "derived": False,
        "value": event.get("user_name", "unknown"),
        "type": "user"
    }
