# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    evt_id = str(event.get("event_id"))

    # 1. Event ID 299 indicates ADFS certificate state loaded or rolled over
    if evt_id == "299":
        # Check if it was done outside of normal system contexts if possible
        # Since it is a rare configuration event, raise medium-high alert
        return 0.75

    # 2. Event ID 4688: Process creation on AD FS server targeting certificate exports
    if evt_id == "4688":
        process = (event.get("process_name") or "").lower()
        cmd = (event.get("command_line") or "").lower()

        # Check for certificate export tools
        export_tools = ["certutil", "powershell", "pwsh"]
        is_tool = any(t in process for t in export_tools)

        if is_tool:
            # Check for export commands
            export_indicators = [
                "export-certificate", "export-pfxcertificate", "-exportpfx",
                "export-certificate", "-export", "get-adfssslcertificate"
            ]
            for ind in export_indicators:
                if ind in cmd:
                    return 0.75  # Extremely high probability: certificate export detected on server

    return 0.0


def clusters(event):

    return session.get("clusters")

def context(event):
    host = event.get("host")
    user = event.get("source_account_name")
    evt_id = event.get("event_id")
    cmd = event.get("command_line") or "-"

    if evt_id == "299":
        return (
            "An AD FS certificate state change or rollover event (ID 299) was logged on host '%s' "
            "by user '%s'. If this is outside a maintenance window, it could indicate token-signing "
            "certificate manipulation."
        ) % (host, user)
    else:
        return (
            "Potential AD FS token-signing certificate export command executed on host '%s' by user '%s' "
            "with command line: '%s'."
        ) % (host, user, cmd)

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Unsecured Credentials (T1552/004)"

def artifacts():
    return stats.collect(["event_id","host","source_account_name","command_line"])

def correlationArtifacts():
    return ["source_account_name"]

def huntingQueryTemplate():
    return ""

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
