# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "fortigate_system_integrity_monitoring"

def automate():

    return True

def notify():
    return False

def algorithm(event):

    subtype = (event.get("log_subtype") or "").lower()
    event_name = (event.get("event") or "").lower()
    details = (event.get("event_details") or "").lower()

    if subtype != "system":
        return 0.0

    text = event_name + " " + details

    reboot_keywords = [
        "device rebooted",
        "reboot",
        "system restarted",
        "power cycle",
        "boot completed"
    ]

    if any(k in text for k in reboot_keywords):
        return 0.75

    return 0.0


def clusters(event):






    """
    Store the session
    """
    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    device = event.get("source_device_name")
    event_name = event.get("event")
    details = event.get("event_details")
    user = event.get("user_name")

    return (
        "FortiGate device "
        + (device or "Unknown Device")
        + " reported a restart/reboot event"
        + (" initiated by user " + user if user else "")
        + ". Event: "
        + (event_name or "Unknown Event")
        + ". "
        + (details if details else "Unexpected restarts can impact security enforcement, logging, and network availability. Validate whether this activity was planned maintenance or abnormal behavior.")
    )

def criticality():
    return "HIGH"

def tactic():
    return "Impact (TA0040)"

def technique():
    return "Service Stop (T1489)"

def artifacts():
    return stats.collect(["event_action","event","user_name","source_device_name"])

def correlationArtifacts():
    return ["source_device_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_device_name", "unknown"),
        "type": "host"
    }
