from datetime import datetime

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """

    # --- Beaconing ---
    label = "beaconing_domain"
    source = event.get("source_ip")
    timestamp = int(event.get("eventtime") or 0)
    interval = "HOUR_OF_DAY"

    beacon_clusters = stats.beaconing(label, source, interval, timestamp)

    # --- Rarity (domain-based) ---
    features = {
        "domain": event.get("destination_hostname"),
        "source_ip": event.get("source_ip")
    }

    rarity_clusters = stats.rarity("domain", features, 2)

    session.set("beacon_clusters", beacon_clusters)
    session.set("rarity_clusters", rarity_clusters)

    return "Initialized beaconing_to_rare_domain detection"

def window():
    return "30d"

def groupby():
    return ["source_ip"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):

    beacon = session.get("beacon_clusters")
    rarity = session.get("rarity_clusters")

    if not beacon or not rarity:
        return 0.0

    dst_ip = event.get("destination_ip")
    domain = event.get("destination_hostname")

    # --- Basic validation ---
    if not domain:
        return 0.0

    # --- Ignore internal traffic ---
    if dst_ip and (
        dst_ip.startswith("10.") or
        dst_ip.startswith("192.168.") or
        dst_ip.startswith("172.")
    ):
        return 0.0

    # --- Check beaconing ---
    if not beacon.get("detected"):
        return 0.0

    # --- Check rarity ---
    total = 0
    anomalies = 0

    for entry in rarity:
        records = entry.get("records", [])
        total += len(records)
        anomalies += sum(1 for r in records if r.get("anomaly"))

    if total == 0:
        return 0.0

    rarity_score = anomalies / float(total)

    # --- Final decision ---
    if rarity_score > 0:
        return 0.75

    return 0.0


def clusters(event):

    return {
        "beacon": session.get("beacon_clusters"),
        "rarity": session.get("rarity_clusters")
    }

def context(event):

    return (
        "Periodic outbound communication detected from source IP "
        + str(event_data.get('source_ip')) +
        " to a rare external domain "
        + str(event_data.get('destination_hostname')) +
        ". This behavior is highly indicative of command-and-control beaconing activity."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Application Layer Protocol (T1071)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","destination_hostname","destination_port","network_protocol","event_action"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "email"
    }

