# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    action = (event.get("event_action") or "").strip().lower()

    if action == "add account":
        return 0.75

    return 0.0


def clusters(event):


    return session.get("clusters")

def context(event):
    user = event.get("user_name") or "Unknown User"
    account = event.get("target_user") or "Unknown Account"
    safe = event.get("safe_name") or "Unknown Safe"

    return (
        "User '{}' created account '{}' in CyberArk Safe '{}'. "
        "Creation of new managed accounts should be verified to ensure it "
        "was authorized and follows organizational access policies."
    ).format(user, account, safe)

def criticality():
    return "HIGH"

def tactic():
    return "Persistence (TA0003)"

def technique():
    return "Create Account (T1136)"

def artifacts():
    return stats.collect(["user_name","target_user","source_ip","source_hostname","applicationname","event_action"])

def correlationArtifacts():
    return ["target_user"]

def huntingQueryTemplate():
    return ""

def entity(event):
    return {
        "derived": False,
        "value": event.get("target_user", "unknown"),
        "type": "user"
    }
