# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    action = (event.get("event_action") or "").strip().lower()
    message = (event.get("message") or "").strip().lower()

    if action != "retrieve password":
        return 0.0

    if "copy password" in message:
        return 1.0

    return 0.0


def clusters(event):


    return session.get("clusters")

def context(event):
    user = event.get("user_name") or "Unknown User"
    account = event.get("target_user") or "Unknown Account"
    safe = event.get("safe_name") or "Unknown Safe"

    return (
        "User '{}' copied the password for account '{}' from Safe '{}'. "
        "Copying privileged credentials may indicate an attempt to use the "
        "credential outside of CyberArk's managed session controls and should "
        "be reviewed."
    ).format(user, account, safe)

def criticality():
    return "CRITICAL"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Credentials from Password Stores (T1555)"

def artifacts():
    return stats.collect(["user_name","target_user","source_ip","destination_ip","applicationname","event_action","message"])

def correlationArtifacts():
    return ["user_name","target_user"]

def huntingQueryTemplate():
    return ""

def entity(event):
    return {
        "derived": False,
        "value": event.get("target_user", "unknown"),
        "type": "user"
    }
