# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    process = (event.get('process_name') or '').lower()
    command = (event.get('process_command') or '').lower()

    # Only shell processes
    shell_processes = ['bash', 'sh', 'zsh', 'ksh']

    if process not in shell_processes:
        return 0.0

    if any(x in command for x in ['-i', 'bash -i', 'sh -i']):
        return 0.75

    if any(x in command for x in ['-c', 'bash -c', 'sh -c']):
        return 0.75

    # Reverse shell indicators
    if any(x in command for x in ['/dev/tcp/', '>&', '0>&1', 'exec bash']):
        return 0.75

    return 0.0


def clusters(event):


    return session.get("clusters")

def context(event):
    return (
        "Suspicious shell execution detected on host " + str(event_data.get('host')) +
        ". Shell process '" + str(event_data.get('process_name')) +
        "' executed command: " + str(event_data.get('process_command')) +
        ". This may indicate attacker command execution or reverse shell activity."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Execution (TA0002)"

def technique():
    return "Command and Scripting Interpreter (T1059)"

def artifacts():
    return stats.collect(["host","process_name","process_command"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "email"
    }
