# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "2m"

def groupby():
    return ["audit_id"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    corelatedFields = stats.accumulate(['process_command','host','source_ip'])
    for key,value in corelatedFields.items():
        session.set(key,value)
    executed_commands = corelatedFields.get('process_command')

    if any(
        ('bash' in cmd and '/dev/tcp/' in cmd) or
        ('nc' in cmd and '-e' in cmd)
        for cmd in executed_commands
    ):
        stats.dissipate(['process_command','host','source_ip'])
        return 1.0

    return 0.0


def clusters(event):



    return session.get("clusterss")

def context(event):
    host = session.get('host')
    source_ip = session.get('source_ip')
    return "Potential reverse shell spawned on host " + str(host[0]) + " with source IP " + str(source_ip[0])

def criticality():
    return "CRITICAL"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Application Layer Protocol (T1071)"

def artifacts():
    return stats.collect(["host","source_ip","process_command"])

def correlationArtifacts():
    return ["host","source_ip","process_command"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
