# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """

    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_powershell_credential_access_activity_monitoring"

def automate():

    # automation: windows_powershell_credential_access_activity_monitoring
    return True

def notify():
    return False

def algorithm(event):

    if event.get('event_id') != 4688:
        return 0.0

    cmd = (event.get('command_line')).lower()
    process = (event.get('process_name') or "").lower()

    if (
        "powershell.exe" not in process and
        "pwsh.exe" not in process
    ):
        return 0.0

    suspicious_patterns = [

        # Stop Event Log service
        "stop-service eventlog",

        # Disable Event Log service
        "set-service eventlog",
        "startuptype disabled",

        # Service control
        "sc.exe stop eventlog",
        "sc stop eventlog",
        "sc.exe config eventlog",
        "sc config eventlog",

        # Clear logs
        "clear-eventlog",
        "wevtutil cl",
        "wevtutil clear-log",

        # Disable logging channels
        "wevtutil sl",
        "/e:false",

        # Registry modifications
        "microsoft\\windows\\currentversion\\winevt"
    ]

    for pattern in suspicious_patterns:
        if pattern in cmd:
            return 0.5

        return 0.0


def clusters(event):





    """
    Store the session
    """
    return []

def context(event):

    process = event.get("process_name")
    parent = event.get("parent_process_name")
    user = event.get("source_account_name") 
    host = event.get("host")
    cmd = event.get("command_line")

    return (
        "Attempt to disable Windows event logging detected. "
        "PowerShell process '{}' was launched by parent process '{}' "
        "under account '{}' on host '{}'. "
        "Observed command line: '{}'. "
        "The command contains indicators associated with stopping, disabling, "
        "clearing, or modifying Windows Event Logging services and channels. "
        "Such activity may be used by attackers to suppress audit trails and "
        "evade detection during malicious operations."
    ).format(
        process,
        parent,
        user,
        host,
        cmd
    )

def criticality():
    return "MEDIUM"

def tactic():
    return "Defense Evasion (TA0005)"

def technique():
    return "Disable Windows Event Logging (T1562/002)"

def artifacts():
    return stats.collect(["event_id","source_account_name","command_line","process_name","parent_process_name","host"])

def correlationArtifacts():
    return ["source_account_name","command_line"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }
