SERVICE_ACCOUNT_KEYWORDS = [
    "svc",
    "service",
    "sql",
    "backup",
    "deploy",
    "app",
    "adm",
    "admin"
]

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_account_privilege_management"

def automate():

    # automation: windows_account_privilege_management
    return True

def notify():
    return False

def algorithm(event):
    # User account created
    if str(event.get('event_id')) != '4720':
        return 0.0

    account = str(
        event.get('destination_account_name') or ""
    ).lower()

    if not account:
        return 0.0

    # Detect likely service account naming
    if any(keyword in account for keyword in SERVICE_ACCOUNT_KEYWORDS):
        return 0.75

    return 0.0


def clusters(event):


    return session.get("clusterss")

def context(event):
    return (
        "Potential service account creation detected on host '{host}'. "
        "Account '{account}' was created by user '{actor}'. "
        "New service accounts may be used for persistence, scheduled task "
        "execution, automated administrative operations, or privilege abuse. "
        "Validate whether the account creation was authorized and review "
        "associated privilege assignments, group memberships, and subsequent "
        "authentication activity."
    ).format(
        host=event.get('host', 'unknown'),
        account=event.get('destination_account_name', 'unknown'),
        actor=event.get('source_account_name', 'unknown')
    )

def criticality():
    return "HIGH"

def tactic():
    return "Persistence (TA0003)"

def technique():
    return "Create Account (T1136)"

def artifacts():
    return stats.collect(["destination_account_name","source_account_name","event_id"])

def correlationArtifacts():
    return ["destination_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("destination_account_name", "unknown"),
        "type": "accountname"
    }

