# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_execution_and_persistence_activity"

def automate():

    # automation: windows_execution_and_persistence_activity
    return True

def notify():
    return False

def algorithm(event):
    evt_id = str(event.get("event_id", ""))

    if evt_id != "4698":
        return 0.0

    creator = (event.get("source_account_name") or "").lower()
    task_content = (event.get("task_content") or "").lower()

    # ---------------------------------------------------------
    # Ignore machine/service accounts
    # ---------------------------------------------------------

    if creator.endswith("$"):
        return 0.0

    if creator in [
        "system",
        "trustedinstaller",
        "networkservice",
        "localservice"
    ]:
        return 0.0

    # ---------------------------------------------------------
    # Suspicious LOLBins / scripting engines
    # ---------------------------------------------------------

    suspicious_keywords = [
        "powershell",
        "cmd.exe",
        "wscript",
        "cscript",
        "mshta",
        "rundll32",
        "regsvr32",
        "bitsadmin",
        "certutil",
        "wmic",
        "pwsh"
    ]

    for keyword in suspicious_keywords:
        if keyword in task_content:
            return 1.0

    # ---------------------------------------------------------
    # Encoded / obfuscated PowerShell
    # ---------------------------------------------------------

    encoded_indicators = [
        "-enc",
        "encodedcommand",
        "frombase64string",
        "iex(",
        "invoke-expression"
    ]

    for indicator in encoded_indicators:
        if indicator in task_content:
            return 1.0

    # ---------------------------------------------------------
    # Suspicious writable paths
    # ---------------------------------------------------------

    suspicious_paths = [
        "\\appdata\\",
        "\\temp\\",
        "\\users\\public\\",
        "\\programdata\\",
        "\\downloads\\",
        "\\desktop\\"
    ]

    for path in suspicious_paths:
        if path in task_content:
            return 1.0

    # ---------------------------------------------------------
    # Hidden scheduled task
    # ---------------------------------------------------------

    if "<hidden>true</hidden>" in task_content:
        return 1.0

    # ---------------------------------------------------------
    # Elevated task execution
    # ---------------------------------------------------------

    elevated_runlevels = [
        "<runlevel>highestavailable</runlevel>",
        "<runlevel>highest</runlevel>"
    ]

    for level in elevated_runlevels:
        if level in task_content:
            return 1.0

    # ---------------------------------------------------------
    # Suspicious recurrence / persistence frequency
    # ---------------------------------------------------------

    suspicious_intervals = [
        "pt1m",
        "pt5m",
        "pt10m"
    ]

    if "<repetition>" in task_content:
        for interval in suspicious_intervals:
            if interval in task_content:
                return 1.0

    return 0.0


def clusters(event):



    return session.get("clusters")

def context(event):
    acct = event.get("source_account_name")
    host = event.get("host")
    task = event.get("task_name")
    logon_id = event.get("source_logon_id")
    task_content = (event.get("task_content") or "").lower()

    matched_reason = "Suspicious XML content detected"

    suspicious_map = {
        "powershell": "PowerShell execution",
        "cmd.exe": "Command shell execution",
        "wscript": "VBScript execution",
        "cscript": "Script host execution",
        "mshta": "MSHTA execution",
        "rundll32": "DLL execution via rundll32",
        "regsvr32": "DLL registration execution",
        "certutil": "Certutil execution",
        "-enc": "Encoded PowerShell detected",
        "encodedcommand": "Encoded command detected",
        "\\appdata\\": "Execution from AppData",
        "\\temp\\": "Execution from Temp directory",
        "<hidden>true</hidden>": "Hidden scheduled task",
        "<runlevel>highestavailable</runlevel>": "Elevated scheduled task"
    }

    for indicator, reason in suspicious_map.items():
        if indicator in task_content:
            matched_reason = reason
            break

    return (
        "A suspicious Windows Scheduled Task '%s' was created on host '%s' "
        "by account '%s' using logon session '%s'. "
        "Detection reason: '%s'. "
        "This activity may indicate malicious persistence or automated code execution."
    ) % (
        task or "-",
        host or "-",
        acct or "-",
        logon_id or "-",
        matched_reason
    )

def criticality():
    return "HIGH"

def tactic():
    return "Persistence (TA0003)"

def technique():
    return "Scheduled Task/Job (T1053/005)"

def artifacts():
    return stats.collect(["task_content","task_name","source_logon_id","host","source_account_name"])

def correlationArtifacts():
    return ["task_name","source_account_name"]

def huntingQueryTemplate():
    return """SELECT * FROM dictionary
WHERE source_account_name = '{{source_account_name}}'"""

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }
