# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    if str(event.get('event_id')) == '1102':
        return 1.0
    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    return (
        "Security logs were cleared on host " +
        str(event.get('host')) +
        ". This may indicate defense evasion."
    )

def criticality():
    return "CRITICAL"

def tactic():
    return "Defense Evasion (TA0005)"

def technique():
    return "Indicator Removal on Host (T1070)"

def artifacts():
    return stats.collect(["host","event_id","source_account_name"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
