# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    """
    Defines the time window for aggregating events.
    This is optional. If aggregation is not needed, return None.
    Typical formats: '5m' for 5 minutes, '30s' for 30 seconds, '1h' for 1 hour.
    """
    return None

def groupby():
    """
    Groups events by specific attributes from the SIEM schema.
    Example: ['user_email'], ['ip_address'], etc.
    This affects how statistical functions compute counts/sums.
    """
    return []

def investigate():
    """
    Defines the automated investigation to run when this detection triggers.
    Example: 'ip_recon', 'malware_scan', etc.
    """
    return None

def automate():
    """
    Determines whether automated actions should be executed for this detection.
    Returns True if automation is enabled, False otherwise.
    """
    return False

def notify():
    """
    Determines whether an email notification should be sent when this detection triggers.
    Returns True to send notification, False to skip.
    """
    return False

def algorithm(event):

    alert_name = str(event.get("event_alert", "")).lower()

    try:
        port = int(event.get("destination_port", 0))
    except:
        port = 0

    risky_ports = [22, 23, 2323, 445, 3389]

    if "scan" in alert_name and port in risky_ports:
        return 0.75
    return 0.0


def clusters(event):
    """
    Store the session
    """
    return session.get("clusterss")

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    return (
        "Reconnaissance against a sensitive service was detected "
        "where Source ip %s Targeting ip %s on Port %s which generated an Alert %s."
        % (
            event.get("source_ip", "unknown"),
            event.get("destination_ip", "unknown"),
            event.get("destination_port", "unknown"),
            event.get("event_alert", "unknown")
        )
    )

def criticality():
    """
    Defines the criticality level of the detection.
    Options: 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'.
    """
    return "HIGH"

def tactic():
    """
    Maps this detection to a MITRE ATT&CK tactic.
    Example: 'Persistence (TA0003)', 'Credential Access (TA0006)', etc.
    """
    return "Persistence (TA0003)"

def technique():
    """
    Maps this detection to a MITRE ATT&CK technique.
    Example: 'Account Manipulation (T1098)', 'Phishing (T1566)', etc.
    """
    return "Account Manipulation (T1098)"

def artifacts():
    """
    Collects unique values of specified attributes across the event window.
    Uses stats.collect() to gather these artifacts.
    """
    return stats.collect(["source_ip","destination_ip","destination_port","event_alert"])

def correlation():
    """
    Groups events by specific attributes from the SIEM schema.
    Example: ['user_email'], ['ip_address'], etc.
    This affects how statistical functions compute counts/sums.
    """
    return []

def entity(event):
    """
    Identifies the primary entity related to this detection.
    Can be directly from event attribute or derived.
    """
    return {
        "derived": False,
        "value": event.get("user_email", "unknown"),
        "type": "email"
    }
