# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return ["host"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    proc = (event.get('process_name') or '').lower()
    cmd = (event.get('command_line') or '').lower()
    path = (event.get('file_path') or '').lower()

    key = application.get("possible_reflective_loading")

    # Prevent duplicate alerts
    if key is True:
        return 0.0

    if not proc or not cmd:
        return 0.0

    # Scope: PowerShell
    if 'powershell' not in proc and 'pwsh' not in proc:
        return 0.0

    # Strong in-memory / encoded execution indicators
    indicators = [
        'frombase64string',
        'invoke-expression',
        'iex',
        '-enc',
        'downloadstring',
        'new-object system.net.webclient'
    ]

    # Must show strong signs of memory-based execution
    suspicious = any(i in cmd for i in indicators)

    # Fileless condition strengthens confidence
    fileless = not path

    if suspicious and fileless:
        application.put("possible_reflective_loading", True, 3600)
        return 0.75

    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    proc = event_data.get('process_name')
    cmd = event_data.get('command_line')
    host = event_data.get('host')
    user = event_data.get('user_name')

    context = "Possible reflective or in-memory code loading activity detected "

    if proc:
        context += "via process " + str(proc) + " "

    if user:
        context += "executed by user " + str(user) + " "

    if host:
        context += "on host " + str(host) + " "

    if cmd:
        context += "with command showing encoded or memory-based execution patterns "

    context += "This behavior may indicate advanced techniques such as reflective loading or fileless malware execution. Further investigation is recommended."

    return context

def criticality():
    return "HIGH"

def tactic():
    return "Defense Evasion (TA0005)"

def technique():
    return "Reflective Code Loading (T1620)"

def artifacts():
    return stats.collect(["process_name","command_line","user_name","host","composite_id"])

def correlationArtifacts():
    return ["host"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
