# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """


    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_kerberos_and_ticket_activity_monitoring"

def automate():

    # automation: windows_kerberos_and_ticket_activity_monitoring
    return True

def notify():
    return False

def algorithm(event):
    # Only Event ID 4662
    if str(event.get('event_id')) != '4662':
        return 0.0

    user = (
        event.get("source_account_name") or ""
    ).lower()

    # Ignore machine accounts
    if user.endswith("$"):
        return 0.0

    # Ignore known sync/service accounts
    known_replication_accounts = [
        "msol_",
        "aad_",
        "adconnect",
        "adsync",
        "azureadsync"
    ]

    if any(user.startswith(x) for x in known_replication_accounts):
        return 0.0

    # Must be Directory Services access
    if str(event.get("object_server", "")).upper() != "DS":
        return 0.0

    if str(
        event.get("access_mask_hex", "")
    ).lower() != "0x100":
        return 0.0

    properties = str(
        event.get("access_reason_detail", "")
    ).lower()

    if not properties:
        return 0.0

    # DCSync replication GUIDs
    replication_guids = [

        # DS-Replication-Get-Changes
        "1131f6aa-9c07-11d1-f79f-00c04fc2dcd2",

        # DS-Replication-Get-Changes-All
        "1131f6ad-9c07-11d1-f79f-00c04fc2dcd2",

        # DS-Replication-Get-Changes-In-Filtered-Set
        "89e95b76-444d-4c62-991a-0facbeda640c"
    ]
    if not any(guid in properties for guid in replication_guids):
        return 0.0

    redkey = "dcsync_" + user
    try:
        key = application.get(redkey)
    except Exception:
        key = None

    if key in (True, "true", "True"):
        return 0.0


    # Match GUID presence
    if any(guid in properties for guid in replication_guids):
        lock_acquired = application.putifabsent(redkey,True,86400)
        if lock_acquired:
          return 1.0
    return 0.0

    return 0.0


def clusters(event):








    return session.get("clusterss")

def context(event):
    return (
        "Account '{user}' accessed Active Directory replication-related permissions "
        "on host '{host}' through a Directory Service object access event (Event ID 4662). "
        "The activity involved object '{object_name}' and replication control rights that "
        "are commonly observed during DCSync attacks. Attackers can abuse these permissions "
        "to request password hashes directly from Active Directory and obtain credentials "
        "for privileged accounts. Confirm whether '{user}' is an approved replication or "
        "synchronization account and investigate associated authentication, privilege, and "
        "administrative activity for signs of credential theft or unauthorized directory access."
    ).format(
        user=event.get('source_account_name'),
        host=event.get('host'),
        object_name=event.get('object_name')
    )

def criticality():
    return "CRITICAL"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "OS Credential Dumping (T1003/006)"

def artifacts():
    return stats.collect(["source_account_name","host","object_server","access_reason_detail","object_name","object_type","source_logon_id","event_id"])

def correlationArtifacts():
    return ["source_account_name"]

def huntingQueryTemplate():
    return """SELECT * FROM dictionary
WHERE source_account_name = '{{source_account_name}}'"""

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }
