# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """


    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "fortigate_threat_detections_and_preventions"

def automate():

    # automation: fortigate_threat_detections_and_preventions
    return True

def notify():
    return False

def algorithm(event):

    category_desc = (event.get("event_category_desc") or "").lower()
    category_id = (event.get("event_category_id") or "")
    source_ip = event.get("source_ip")
    key = "outbound_malicious_destination_%s" % (source_ip)
    if application.get(key):
            return 0.0

    if not source_ip:
        return 0.0

    risky_keywords = [
        "malicious",
        "phishing",
        "botnet",
        "spam",
        "spyware",
        "trojan",
        "browser exploits",
        "criminal activity",
        "hacking",
        "fraud",
        "scam",
        "suspicious",
        "malware"
    ]

    risky_ids = [
        "128","154","164","166","167","172",
        "193","194","200","205","206","207",
        "213","214","218","219","220"
    ]

    if any(k in category_desc for k in risky_keywords):
        application.put(key, True, 86400)
        return 0.75

    if category_id in risky_ids:
        application.put(key, True, 86400)
        return 0.75

    return 0.0


def clusters(event):





    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    source_ip = event.get("source_ip")
    source_port = event.get("source_port")
    destination_port = event.get("destination_port")
    user_name = event.get("user_name")
    destination_ip = event.get("destination_ip")
    destination_country = event.get("destination_country")
    network_protocol = event.get("network_protocol")
    applicationname = event.get("applicationname")
    category_desc = event.get("event_category_desc")
    policy_id = event.get("policy_id")
    url = event.get("url")
    details = event.get("event_details")
    network_bytes = str(event.get("network_bytes_transferred"))

    return (
        "An outbound connection was detected from source IP "
        + (source_ip or "Unknown Source")
        + (" using source port " + source_port if source_port else "")
        + (" accessing the URL " + url if url else "")
        + ", which was flagged as "
        + (category_desc or "Unknown Category")
        + ". The destination IP was "
        + (destination_ip or "Unknown Destination")
        + (" on port " + destination_port if destination_port else "")
        + (" located in " + destination_country if destination_country else "")
        + ". The traffic used the protocol/service "
        + (network_protocol or "Unknown")
        + (" and transferred " + network_bytes + " bytes" if network_bytes else "")
        + " in the outbound direction. "
        + (details or "No additional details were provided")
        + " under policy ID "
        + (policy_id or "Unknown")
        + ", indicating potential communication with unsafe or compromised infrastructure."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Command and Control(TA0011)"

def technique():
    return "Application Layer Protocol (T1071)"

def artifacts():
    return stats.collect(["event_category_id","source_ip","network_protocol","destination_country","event_category_desc","destination_ip","url","destination_port","source_port","policy_id","host_domain"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
