# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["source_ip"]

def investigate():
    return "windows_authentication_logon_anomalies"

def automate():

    # automation: windows_authentication_logon_anomalies
    return True

def notify():
    return False

def algorithm(event):

    # only failed logons
    if str(event.get("event_id")) != "4625":
        return 0.0

    src_ip = event.get("source_ip")
    acct = (event.get("destination_account_name") or "").strip()
    logon_type = event.get("logon_type")
    status = (event.get("sub_status") or "").lower()

    # ignore noise
    if not src_ip or src_ip in ["-", "UNKNOWN", "127.0.0.1", "::1"]:
        return 0.0

    if not acct or acct.endswith("$"):
        return 0.0

    # meaningful authentication only
    if logon_type not in ["2", "3", "10"]:
        return 0.0

    #  username enumeration = invalid user
    if status != "0xc0000064":
        return 0.0
    try:
        key = application.get("repeated_failed_logons_using_nonExistent_username")
    except Exception:
        key = None

    if key in (True, "true", "True"):
        return 0.0
    #  track unique usernames per IP
    stat_key = "username_enumeration_via_invalid_logon" 
    count = stats.count(stat_key)

    if count > 10:
        stats.resetcount(stat_key)
        lock_acquired = application.putifabsent("repeated_failed_logons_using_nonExistent_username",True,86400)
        if lock_acquired:
          return 0.5

    return 0.0


def clusters(event):

    return session.get("clusters")

def context(event):
    return (
        "Multiple failed Windows logon attempts using a non-existent username were detected "
        "from source IP " + str(event.get("source_ip")) + ". "
        "The authentication attempts failed because the specified account does not exist. "
        "This activity may indicate automated authentication attempts, malware retries, "
        "misconfigured services, or brute-force behavior targeting invalid accounts."
    )

def criticality():
    return "MEDIUM"

def tactic():
    return "Discovery (TA0007)"

def technique():
    return "Account Discovery (T1087)"

def artifacts():
    return stats.collect(["source_ip","destination_account_name","host","logon_type","event_id"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
