from datetime import datetime, timedelta

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    analysis = stats.zanomaly("network_bytes_out")
    session.set("anomalies", [analysis])
    return "Initialized zanomaly detection"

def window():
    return "15m"

def groupby():
    return ["source_ip"]

def investigate():
    return "fortigate_outbound_threat_monitoring"

def automate():

    # automation: fortigate_outbound_threat_monitoring
    return True

def notify():
    return False

def algorithm(event):
    timestamp = event.get("timestamp")
    action = str(event.get("event_action") or "").lower()
    src = event.get("source_ip")
    dst = event.get("destination_ip")
    direction = event.get("network_direction")

    if not timestamp or not src or not dst:
        return 0.0

    if action not in ["allow", "accept", "permit"]:
        return 0.0

    if direction and direction == 'outbound':
            hour = _event_hour(event)
            if hour is None:
                return 0.0

            if hour >= 23 or hour < 7:
                analysis = session.get("anomalies")[0]
                anomaly = analysis.get("anomaly")

                if anomaly == 1:
                    return 0.75

    return 0.0


def clusters(event):

    return session.get("anomalies")

def context(event):

    analysis = session.get("anomalies")[0]
    mean = analysis.get("mean")

    return (
        "Unusual outbound data transfer detected from source IP "
        + (event.get("source_ip"))
        + " to destination IP "
        + (event.get("destination_ip"))
        + " during off-hours. "
        + (event.get("network_bytes_out"))
        + " bytes were sent, which is anomalous compared to the baseline mean of "
        + str(mean)
        + " bytes for this source."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Exfiltration (TA0010)"

def technique():
    return "Exfiltration Over Network (T1041)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","network_bytes_out","destination_port","network_protocol"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }


def _event_hour(event):
    ts = event.get("timestamp")
    if not ts:
        return None

    try:
        dt = datetime.utcfromtimestamp(int(ts) / 1000.0) + timedelta(hours=5, minutes=30)
        return dt.hour
    except Exception:
        return None