# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "2m"

def groupby():
    return ["source_ip"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    process = event.get('process_name')
    action = (event.get('event_action') or '').lower()
    details = (event.get('event_details') or '').lower()

    if process == 'sshd' and action == 'failed' and (
        'failed password for' in details or 
        'authentication failure' in details
    ):
        if stats.count('source_ip') == 6:
            stats.resetcount('source_ip')
            return 0.50
    return 0.0


def clusters(event):




    return session.get("clusterss")

def context(event):
    return "Multiple failed SSH login attempts detected on the host " + str(event.get('host'))  + " by user " + str(event.get('user')) + " using IP "+ str(event.get('source_ip')) + " with more than 5 attempts in 2 minutes."

def criticality():
    return "MEDIUM"

def tactic():
    return "Initial Access (TA0001)"

def technique():
    return "Brute Force (T1110)"

def artifacts():
    return stats.collect(["host","source_ip","process_name","user","process_id"])

def correlationArtifacts():
    return ["user","host","source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "email"
    }
