# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return ["destination_ip"]

def investigate():
    return "fortigate_vpn_security_monitoring"

def automate():

    # automation: fortigate_vpn_security_monitoring
    return True

def notify():
    return False

def algorithm(event):
    #this detection have been recreated with user instead of ipaddress
    event_level = event.get("event_level")
    action = event.get("event_action")
    key = application.get("alert_level")

    if not action:
        return 0.0

    if key is True:
        return 0.0

    if event_level == "1" and action == "ssl-login-fail":
        application.put("alert_level", True, 86400)
        return 0.75
    return 0.0


def clusters(event):






    """
    Store the session
    """
    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """



    event_str = event.get("event")
    user = event.get("user_name")
    country = event.get("source_country")
    type = event.get("log_subtype")
    device = event.get("source_device_name")
    ip = event.get("destination_ip")
    tunnel = event.get("tunnel_type")
    context = "A Fortigate firewall logged an alert-level event that may indicate a security issue "
    if event_str:
      context += "due to  " + event_str + " "
    if user:
      context += "for user " + user + " "
    if country:
      context += "from source country " + country + " "
    if ip:
      context += "with destination ip " + ip + " "
    if tunnel:
      context += "and tunnel type " + tunnel + " "
    if type:
      context += "while using " + type + " "
    if device:
      context += "for device " + device + " "
    context += "Review the event to verify system and take corrective action if needed."
    return context

def criticality():
    return "HIGH"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Application Layer Protocol (T1071)"

def artifacts():
    return stats.collect(["user_name","log_subtype","event_action","source_country","destination_ip","tunnel_type"])

def correlationArtifacts():
    return ["user_name","destination_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("destination_ip", "unknown"),
        "type": "ipaddress"
    }
