# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "30m"

def groupby():
    return ["source_ip"]

def investigate():
    return "fortigate_vpn_security_monitoring"

def automate():

    # automation: fortigate_vpn_security_monitoring
    return True

def notify():
    return False

def algorithm(event):


    subtype = event.get("log_subtype")
    action = event.get("event_action")
    key = application.get("vpn_login")
    country = event.get("destination_country")

    if key is True:
        return 0.0

    if not subtype or not action or not country:
        return 0.0

    # Trigger if subtype is "system" and ANY keyword appears in the log message
    if subtype!="vpn" or action!="login":
        return 0.0

    if country in ["UNKNOWN", "RESERVED", ""]:
        return 0.0

    dest_country = stats.accumulate(['destination_country'])
    unique_country=len(dest_country.get("destination_country"))
    if unique_country >= 3:
      stats.dissipate(['destination_country'])
      lock_acquired = application.putifabsent("destination_country", True, 86400)
      if lock_acquired:
        return 1.0
    return 0.0


def clusters(event):






    """
    Store the session
    """
    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    # Safely extract relevant FortiGate VPN log values with defaults
    src_ip = event.get('source_ip')
    geo_country = event.get('destination_country')
    device = event.get('source_device_name')
    subtype = event.get("log_subtype")
    action = event.get("event_action")

    # Build the narrative
    message = (
        "The device {device} observed multiple VPN login sessions "
        "from 5 different geographic locations, including {geo_country} (source IP: {src_ip}). "
        "The event shows type {subtype} with action {action}. "
        "This pattern may indicate credential sharing or potential account compromise, "
        "as simultaneous or rapid logins from distant regions are atypical for normal user behavior."
    ).format(
        device=device,
        geo_country=geo_country,
        src_ip=src_ip,
        subtype=subtype,
        action=action

    )

    return message

def criticality():
    return "CRITICAL"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Valid Accounts (T1078)"

def artifacts():
    return stats.collect(["destination_country","source_ip","destination_ip","log_subtype"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
