SERVICE_ACCOUNTS = [
    "PasswordManager",
    "PVWAAppUser",
    "PSMApp_"
]

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):


    action = (event.get("event_action") or "").strip().lower()
    user = (event.get("user_name") or "").strip().lower()

    # Ignore CyberArk service accounts
    for account in SERVICE_ACCOUNTS:
        if user.startswith(account):
            return 0.0

    if action == "clear safe history":
        return 1.0

    return 0.0


def clusters(event):


    return session.get("clusters")

def context(event):
    user = event.get("user_name") or "Unknown User"
    safe = event.get("safe_name") or "Unknown Safe"

    return (
        "User '{}' cleared the audit history of CyberArk Safe '{}'. "
        "Clearing Safe history may remove historical audit records and "
        "should be reviewed to ensure it was an authorized administrative action."
    ).format(user, safe)

def criticality():
    return "CRITICAL"

def tactic():
    return "Defense Evasion (TA0005)"

def technique():
    return "Indicator Removal (T1070)"

def artifacts():
    return stats.collect(["user_name","source_ip","source_hostname","applicationname","event_action"])

def correlationArtifacts():
    return ["user_name"]

def huntingQueryTemplate():
    return ""

def entity(event):
    return {
        "derived": False,
        "value": event.get("user_name", "unknown"),
        "type": "user"
    }

