# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "30m"

def groupby():
    return ["source_ip"]

def investigate():
    return "fortigate_outbound_threat_monitoring"

def automate():

    # automation: fortigate_outbound_threat_monitoring
    return True

def notify():
    return False

def algorithm(event):


    dst_ip = event.get("destination_ip")
    country = event.get("destination_country")
    bytes_out = event.get("network_bytes_out")
    key = application.get("data_exfilteration_country")

    if key is True:
        return 0.0

    if not dst_ip or not country or not bytes_out:
        return 0.0

    # Ignore internal traffic
    incidrrange = cidr.inRange(dst_ip, [
        "14.141.115.58/30",
        "14.142.192.128/30",
        "125.17.69.248/30",
        "61.95.141.98/30",
        "203.194.111.106/32",
        "100.122.137.60/32",
        "100.76.126.248/32",
        "115.111.247.166/30",
        "103.176.170.64/29",
        "103.155.57.72/29",
        "14.140.210.208/30",
        "103.137.218.98/29",
        "122.185.181.54/30",
        "203.112.158.244/29",
        "103.26.201.244/29",
        "103.26.201.252/29",
        "103.26.201.0/24",
        "182.66.121.26/30",
        "14.97.152.142/30",
        "122.186.71.70/30",
        "14.143.159.224/30",
        "122.187.39.102/30",
        "203.122.8.200/29",
        "136.232.144.116/30",
        "136.232.142.132/30",
        "203.200.68.0/24",
        "14.140.162.248/29",
        "125.22.24.16/29",
        "115.112.32.192/29",
        "14.142.33.176/28",
        "59.160.104.0/24",
        "122.187.57.64/27",
        "47.29.213.16/29"
    ])

    if incidrrange:
        return 0.0

    bytes_out = int(bytes_out)

    # Ignore small transfers
    if bytes_out < 10000000:  # 10MB
        return 0.0

    # Check rarity of country
    rare_country = stats.rarity("destination_country")

    if rare_country == 1.0:
        application.put("data_exfilteration_country", True, 86400)
        return 0.75

    return 0.0


def clusters(event):

    """
    Store the session
    """
    return "initialization completed"

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """

    return (
        "Large outbound data transfer detected from source IP "
        + str(event.get("source_ip")) +
        " to destination IP "
        + str(event.get("destination_ip")) +
        " located in a rare country ("
        + str(event.get("destination_country")) +
        "). The data transfer volume was "
        + str(event.get("network_bytes_out")) +
        " bytes, which may indicate potential data exfiltration."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Exfiltration (TA0010)"

def technique():
    return "Exfiltration Over Network (T1041)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","destination_country","network_bytes_out","destination_port","network_protocol"])

def correlationArtifacts():
    return ["destination_country","source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
