# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "15m"

def groupby():
    return ["user"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    process = event.get('process_name')
    details = (event.get('event_details') or '').lower()
    user = event.get('user')

    if process == 'sudo' and user != 'root' and 'session opened for user root' in details:
        if stats.count('abnormal_sudo') >= 15:
          stats.resetcount('abnormal_sudo')
          return 0.75

    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    return (
        "Abnormal sudo privilege escalation detected. "
        "User " + str(event.get('user')) +
        " initiated a sudo sessions to root " +
        " on host " + str(event.get('host')) + " with 15 sessions in 15 minutes duration" +
        ". This may indicate unauthorized privilege escalation and should be reviewed."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Privilege Escalation (TA0004)"

def technique():
    return "Abuse Elevation Control Mechanism (T1548)"

def artifacts():
    return stats.collect(["host","process_name","user","event_details","event_action"])

def correlationArtifacts():
    return ["host","process_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("user_name", "unknown"),
        "type": "email"
    }
