# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "fortigate_threat_detections_and_preventions"

def automate():

    # automation: fortigate_threat_detections_and_preventions
    return True

def notify():
    return False

def algorithm(event):
    alert = str(event.get("event_alert") or "").lower()
    details = str(event.get("event_details") or "").lower()
    source_ip = event.get("source_ip")
    destination_ip = event.get("destination_ip")

    if not source_ip:
        return 0.0

    text = alert + " " + details

    if "tcp.split.handshake" not in text and "tcp split handshake" not in text:
        return 0.0

    key = "tcp_split:" + str(source_ip) + ":" + str(destination_ip or "any")

    if application.get(key) is True:
        return 0.0

    application.put(key, True, 86400)

    return 0.50


def clusters(event):




    return session.get("clusterss")

def context(event):

    src_ip = event.get("source_ip")
    src_port = event.get("source_port")
    dst_ip = event.get("destination_ip")
    dst_port = event.get("destination_port")
    country = event.get("destination_country")
    protocol = event.get("network_protocol")
    device = event.get("source_device_name")
    details = event.get("event_details")
    alert = event.get("event_alert")

    return (
        "FortiGate detected a TCP split handshake attempt from "
        + (src_ip or "Unknown Source")
        + (":" + str(src_port) if src_port else "")
        + " to "
        + (dst_ip or "Unknown Destination")
        + (":" + str(dst_port) if dst_port else "")
        + (" located in " + country if country else "")
        + ". Service/protocol: "
        + (protocol or "Unknown")
        + ". Device: "
        + (device or "Unknown Device")
        + ". Signature: "
        + (alert or "TCP Split Handshake")
        + ". "
        + (details if details else "This may indicate an attempt to evade stateful inspection or bypass network defenses.")
    )

def criticality():
    return "MEDIUM"

def tactic():
    return "Defense Evasion (TA0005)"

def technique():
    return "Exploitation for Defense Evasion (T1211)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","event_alert","network_protocol","event_action"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
