# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["source_ip"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):

    event_type = event.get('event_type')
    process_path = event.get('process_path')
    event_details = event.get('event_details')
    if event_type = 'USER_LOGIN' and process_path - '/usr/sbin/sshd' and event_details = 'failed':
        if stats.count('ssh_brute_force') > 5 :
            return 0.75
    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    return "Multiple failed SSH login attempts detected on host " + str(event_data.get('host')) + 
           " targeting user " + str(event_data.get('user')) + 
           " from source IP " + str(event_data.get('source_ip')) + 
           ". All attempts were unsuccessful within a short time window, indicating a potential brute-force or password guessing attack."

def criticality():
    return "HIGH"

def tactic():
    return "Lateral Movement (TA0008)"

def technique():
    return "Remote Services (T1021)"

def artifacts():
    return stats.collect(["host","process_name","user","event_action","source_ip","source_port","event_details"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
