# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "1d"

def groupby():
    return ["host"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    img   = str(event.get('process_name') or '').lower()
    cmd   = str(event.get('command_line') or '').lower()
    parent= str(event.get('parent_process_name') or '').lower()

    # Common account discovery tools or commands
    acc_tools = [
        'net.exe', 'net1.exe', 'query.exe', 'powershell.exe', 'wmic.exe', 'dsquery.exe'
    ]
    acc_cmds = [
        'net user', 'net group', 'net localgroup', 'net accounts',
        'query user', 'query session', 'query group', 'wmic useraccount get',
        'get-localuser', 'get-aduser', 'get-adgroup', 'get-adgroupmember',
        'get-wmiobject win32_useraccount', 'dsquery user', 'dsquery group'
    ]
    is_tool = any(t in img for t in acc_tools) or any(c in cmd for c in acc_cmds)

    sus_parent = any(parent.endswith(x) for x in [
        'winword.exe','excel.exe','outlook.exe','wscript.exe','cscript.exe','explorer.exe'
    ])

    if is_tool or sus_parent:
        stats.count('account_discovery')
        c = stats.getcount('account_discovery')
        if c == 2:
            return 1.0
        return 0.75

    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    proc = str(event_data.get('source_process_name') or '')
    cmd  = str(event_data.get('command_line') or '')
    par  = str(event_data.get('parent_process_name') or '')
    return (
        "Possible Account Discovery activity detected. "
        "The  process '" + proc + "' was executed by parent process '" + par + 
        "' with command line: \"" + cmd + "\". "
        "This behavior is consistent with attempts to enumerate local or domain user accounts "
        "(using tools such as net, query, PowerShell Get-ADUser, or dsquery). "
        "Verify if this activity originated from an authorized administrative task or automation script."
    )

def criticality():
    return "CRITICAL"

def tactic():
    return "Discovery (TA0007)"

def technique():
    return "Account Discovery (T1087)"

def artifacts():
    return stats.collect([])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
