# Auto-generated by BinaryFlux UI Builder
# Netskope DLP Detection


def init(event):
    try:
        session.set("event", event)
        return "initialized"
    except Exception:
        return None


def window():
    return None


def groupby():
    return []


def investigate():
    return None


def automate():
    return False


def notify():
    return False


def algorithm(event):

    alert_type = (event.get("alert_type") or "").lower()

    if alert_type not in ["dlp", "policy"]:
        return 0.0

    severity = (event.get("event_severity") or "").lower()

    if severity == "low":
        return 0.25

    if severity == "informational":
        return 0.25

    if severity == "medium":
        return 0.50

    if severity == "high":
        return 0.75

    if severity == "critical":
        return 1.0

    return 0.50


def clusters(event):
    return []


def context(event):

    rule = (
        event.get("dlp_rule")
        or event.get("policy_name")
        or event.get("alert_name")
        or "unknown"
    )

    return (
        "Netskope detected a DLP policy violation matching rule '{rule}'. "
        "Sensitive data was identified during a '{activity}' activity. "
        "User '{user}' performed the action using application '{app}'. "
        "Netskope enforced action '{action}'."
    ).format(
        rule=rule,
        user=event.get("user_name", "unknown"),
        activity=event.get("event_action", "unknown"),
        app=event.get("applicationname", "unknown"),
        action=event.get("action_type", "unknown")
    )


def criticality():


        event = session.get("event")

        severity = (event.get("event_severity") or "").lower()

        if severity == "poor":
            return "LOW"

        if severity == "low":
            return "LOW"

        if severity == "medium":
            return "MEDIUM"

        if severity == "high":
            return "HIGH"

        if severity == "critical":
            return "CRITICAL"

        return "MEDIUM"



def tactic():
    return "Exfiltration (TA0010)"

def technique():
    return "Exfiltration Over Web Service (T1567)"


def artifacts():

    return stats.collect([
        "host",
        "user_name",
        "source_ip",
        "destination_ip",
        "url",
        "destination_domain",
        "file_hash",
        "dlp_rule",
        "policy_id"
    ])


def correlationArtifacts():
    return ["host", "user_name"]


def entity(event):

    return {
        "derived": False,
        "value": event.get("user_name", "unknown"),
        "type": "user"
    }
    