# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_powershell_credential_access_activity_monitoring"

def automate():

    # automation: windows_powershell_credential_access_activity_monitoring
    return True

def notify():
    return False

def algorithm(event):
    if str(event.get("event_id") or "") != "4688":
        return 0.0

    process = str(event.get("process_name") or "").lower()
    cmd = str(event.get("command_line") or "").lower()

    if (
        "powershell.exe" not in process and
        "pwsh.exe" not in process
    ):
        return 0.0

    suspicious = (
        "-enc " in cmd or
        "-encodedcommand" in cmd or
        "-ep bypass" in cmd or
        "-executionpolicy bypass" in cmd
    )

    if suspicious:
        return 0.75

    return 0.0


def clusters(event):


    return session.get("clusterss")

def context(event):
    process = event.get("process_name") or "unknown"
    parent = event.get("parent_process_name") or "unknown"
    user = event.get("source_account_name") or "unknown"
    host = event.get("host") or "unknown"
    cmd = event.get("command_line") or "unavailable"

    return (
        "Encoded PowerShell execution detected. "
        "Process '{}' was launched by parent process '{}' "
        "under account '{}' on host '{}'. "
        "Observed command line: '{}'. "
        "Encoded PowerShell commands are frequently used to conceal script content, "
        "evade security controls, execute malicious payloads, or perform post-exploitation activities."
    ).format(
        process,
        parent,
        user,
        host,
        cmd
    )

def criticality():
    return "HIGH"

def tactic():
    return "Execution (TA0002)"

def technique():
    return "PowerShell (T1059.001)"

def artifacts():
    return stats.collect(["event_id","process_name","source_account_name","parent_process_name","command_line"])

def correlationArtifacts():
    return ["process_name","command_line","source_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("process_name", "unknown"),
        "type": "email"
    }
