# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "10m"

def groupby():
    return ["source_ip"]

def investigate():
    return "fortigate_system_integrity_monitoring"

def automate():

    # automation: fortigate_system_integrity_monitoring
    return True

def notify():
    return False

def algorithm(event):

    alert_type = event.get('event_alert')
    key = application.get("admin_fail_login")

    if key is True:
        return 0.0

    if alert_type in ['internal_error', 'passwd_invalid', 'name_invalid']:
        if stats.count("admin_failed") == 15:
            application.put("admin_fail_login", True, 86400)
            stats.resetcount("admin_failed")
            return 0.75
    return 0.0


def clusters(event):






    """
    Store the session
    """
    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    return str(event.get('event_details'))

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Brute Force (T1110)"

def artifacts():
    return stats.collect(["event_action","event_alert","source_ip","destination_ip","user_name"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
