# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """


    return []

def window():
    return "10m"

def groupby():
    return ["source_account_name"]

def investigate():
    return "windows_authentication_logon_anomalies"

def automate():

    # automation: windows_authentication_logon_anomalies
    return True

def notify():
    return False

def algorithm(event):
    user = event.get('source_account_name') or ""
    event_id = str(event.get("event_id") or "")
    logon_type = str(event.get("logon_type") or "")

    # Ignore noise
    if not user or user in ["UNKNOWN", "-", "_"]:
        return 0.0

    if user.endswith("$"):
        return 0.0

    if logon_type == "5":
        return 0.0

    if logon_type == "3":
      ip = event.get("source_ip") or ""

      if ip in ["", "-", "UNKNOWN"]:
          return 0.0

    try:
        key = application.get("windows_successful_logon_after_multiple_failures")
    except Exception:
        key = None

    if key in (True, "true", "True"):
        return 0.0

    # Count failures
    if event_id == "4625":
        stats.count("successful_logon_after_multiple_failures_count")

    failures = int(stats.getcount("successful_logon_after_multiple_failures_count") or 0)

    if event_id == "4624":
        if failures > 5 :
            session.set("count", stats.count("successful_logon_after_multiple_failures_count"))
            stats.resetcount("successful_logon_after_multiple_failures_count")
            lock_acquired = application.putifabsent("windows_successful_logon_after_multiple_failures",True,86400)
            if lock_acquired:
              return 0.75

    return 0.0


def clusters(event):






    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """

    user = event.get("source_account_name") 
    host = event.get("host") 
    ip = event.get("source_ip") 
    failures = int(session.get("count"))

    return (
        "User '" + user +
        "' successfully logged in after " + str(failures) +
        " failed login attempts within 10 minutes "
        "from IP '" + ip +
        "' on host '" + host +
        "'. This may indicate a brute-force or password guessing attack."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Brute Force (T1110)"

def artifacts():
    return stats.collect(["event_id","host","source_account_name","source_ip","logon_type"])

def correlationArtifacts():
    return ["source_account_name"]

def huntingQueryTemplate():
    return """SELECT * FROM dictionary
WHERE source_account_name = '{{source_account_name}}' AND destination_account_name = '{{destination_account_name}}' AND event_id IN ('4624', '4625')"""

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }
