# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """

    return "initialization completed"

def window():
    return "10m"

def groupby():
    return ["destination_account_name"]

def investigate():
    return "windows_authentication_logon_anomalies"

def automate():

    # automation: windows_authentication_logon_anomalies
    return True

def notify():
    return False

def algorithm(event):

    acct = (event.get('destination_account_name') or "").strip()
    source_ip = event.get('source_ip')
    logon_type = str(event.get('logon_type') or "")
    event_id = str(event.get('event_id') or "")

    if event_id != "4625":
        return 0.0

    if acct and acct.endswith('$'):
        return 0.0

    if not source_ip or source_ip in ['::1', 'UNKNOWN', '127.0.0.1', '-']:
        return 0.0

    if logon_type not in ["2", "3", "10"]:
        return 0.0

    try:
        key = application.get("high_frequency_failed_logons_for_account")
    except Exception:
        key = None

    if key in (True, "true", "True"):
        return 0.0

    if stats.count('high_frequency_failed_logons_for_account_name') == 5:
        stats.resetcount('high_frequency_failed_logons_for_account_name')
        application.put("high_frequency_failed_logons_for_account", True, 86400)
        return 0.75

    return 0.0

    # acct = (event.get('destination_account_name') or "").strip()
    # source_ip = event.get('source_ip')
    # logon_type = event.get('logon_type')
    # try:
    #     key = application.get("high_frequency_failed_logons_for_account")
    # except Exception:
    #     key = None

    # # If already triggered recently, skip
    # if  key in (True, "true", "True"):
    #     return 0.0

    # if acct and acct.endswith('$'):
    #     return 0.0
    # if not source_ip or source_ip in ['::1', 'UNKNOWN', '127.0.0.1', '-']:
    #   return 0.0
    # if logon_type not in ["2", "3", "10"]:
    #     return 0.0


    # if event.get('event_id') == "4625":
    #     if stats.count('high_frequency_failed_logons_for_account_name') > 5:
    #         stats.resetcount('high_frequency_failed_logons_for_account_name')
    #         application.put("high_frequency_failed_logons_for_account", True, 86400)
    #         return 0.75
    # return 0.0


def clusters(event):





    return []

def context(event):
    account = event.get('destination_account_name') or "unknown account"
    host = event.get('host') or "unknown host"
    source_ip = event.get('source_ip') or "unknown source"
    logon_type = event.get('logon_type') or "unknown"
    process = event.get('process_name') or "unknown process"
    status = (event.get('sub_status') or "").lower()

    if status == "0xc000006a":
        reason = "incorrect password attempts"
    elif status == "0xc0000064":
        reason = "invalid or non-existent usernames"
    else:
        reason = "authentication failures"

    return (
        "High-frequency failed logon attempts detected for account "
        + str(account)
        + " on host "
        + str(host)
        + ". "
        "Multiple "
        + reason
        + " were observed within a short time window, "
        "originating from source IP "
        + str(source_ip)
        + " using logon type "
        + str(logon_type)
        + ". "
        "The activity is associated with process "
        + str(process)
        + ", which may indicate a brute-force attack, password spray, or a misconfigured service using stale credentials."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Brute Force (T1110)"

def artifacts():
    return stats.collect(["source_ip","event_type","host","destination_account_name","event_id","logon_type","process_name"])

def correlationArtifacts():
    return ["destination_account_name","source_ip"]

def huntingQueryTemplate():
    return """SELECT * FROM dictionary
WHERE source_ip = '{{source_ip}}' AND destination_account_name = '{{destination_account_name}}' AND event_id IN ('4625')"""

def entity(event):
    return {
        "derived": False,
        "value": event.get("destination_account_name", "unknown"),
        "type": "accountname"
    }
