# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "10m"

def groupby():
    return ["host"]

def investigate():
    return "windows_execution_and_persistence_activity"

def automate():

    # automation: windows_execution_and_persistence_activity
    return True

def notify():
    return False

def algorithm(event):
    evt_id = str(event.get("event_id"))
    if evt_id != "7045":
        return 0.0
    host = event.get("host")
    service_name = event.get("service_name")
    binary_path = event.get("service_binary_path")
    account = event.get("service_account")
    start_type = event.get("service_start_type")
    installed_by = event.get("source_account_name")

    # Normalize strings for comparison
    path_l = (binary_path or "").lower()
    svc_name_l = (service_name or "").lower()

    # --- Whitelist known legitimate vendor/service installs (customize per environment) ---
    benign_patterns = [
        "windows defender", "microsoft update", "vmtools",
        "citrix", "crowdstrike", "carbonblack", "qualys",
        "tanium", "sccm", "intune"
    ]
    for b in benign_patterns:
        if b in path_l or b in svc_name_l:
            return 0.0

    # --- Suspicious binary locations (often abused by attackers) ---
    suspicious_paths = [
        "\\temp\\", "\\appdata\\", "\\users\\public\\",
        "\\programdata\\", "\\windows\\tasks", "\\windows\\debug\\",
        "\\windows\\system32\\spool\\drivers\\color\\"
    ]
    for sp in suspicious_paths:
        if sp in path_l:
            return 0.9  # High confidence: service binary in non-standard or user-writable location

    # --- Suspicious service account usage ---
    if account and account.lower() not in ["localsystem", "localservice", "networkservice"]:
        return 0.75  # Custom or high-privilege account used — potential persistence

    # --- Suspicious auto-start behavior ---
    if start_type and "auto" in start_type.lower():
        return 0.6  # Auto-start service indicates persistence mechanism

    # --- Fallback: low confidence for any non-whitelisted new service ---
    return 0.3


def clusters(event):


    return session.get("clusterss")

def context(event):
    host = event.get("host")
    service_name = event.get("service_name") or "-"
    binary_path = event.get("service_binary_path") or "-"
    account = event.get("service_account") or "-"
    start_type = event.get("service_start_type") or "-"
    installed_by = event.get("source_account_name") or "-"

    return (
        "A new Windows service '%s' was installed on host '%s' (binary: '%s', "
        "account: '%s', start type: '%s', installed by: '%s'). "
        "Installing new services is often used to maintain persistence or execute malicious code."
    ) % (service_name, host, binary_path, account, start_type, installed_by)

def criticality():
    return "HIGH"

def tactic():
    return "Persistence (TA0003)"

def technique():
    return "Create or Modify System Process (T1543/003)"

def artifacts():
    return stats.collect(["event_id","host","service_name","service_binary_path","service_account","service_start_type","source_account_name"])

def correlationArtifacts():
    return ["service_name","source_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
