# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["destination_ip","destination_port"]

def investigate():
    return "fortigate_network_traffic_anomaly_detection"

def automate():

    # automation: fortigate_network_traffic_anomaly_detection
    return True

def notify():
    return False

def algorithm(event):
    src_ip = str(event.get('source_ip') or '')
    dst_ip = str(event.get('destination_ip') or '')
    dst_port = str(event.get('destination_port') or '')
    action = str(event.get('event_action') or '').lower()
    role = str(event.get('destination_device_interface_role') or '').lower()
    protocol = str(event.get('network_protocol') or '').upper()
    direction = (event.get("network_direction")or "").lower()

    if action != "deny":
      return 0.0

    if not dst_ip or not dst_port or not src_ip:
      return 0.0

    cache_key = "multiple_internal_src_deny:" + dst_ip        	
    if application.get(cache_key):
      return 0.0

    sources_ips = stats.collect(["source_ip"])
    distinct_src_ips = len(sources_ips.get("source_ip", set()))

    if distinct_src_ips > 10:
      application.put(cache_key, True, 86400)
      return 0.85

    return 0.0


def clusters(event):

    return session.get("clusters")

def context(event):
    dst_ip = event.get('destination_ip', 'unknown')
    dst_port = event.get('destination_port', 'unknown')
    policy = event.get('policy_name') or event.get('firewall_rule_name') or event.get('policyname') or 'unknown'
    service = event.get('network_service') or event.get('service') or 'unknown'
    crlevel = event.get('risk_level') or event.get('crlevel') or 'unknown'

    collected = stats.collect(["source_ip", "source_device_name"])
    source_ips = collected.get("source_ip", set())
    source_devices = collected.get("source_device_name", set())

    message = (
        "Multiple internal source IPs were denied by the Fortigate firewall while attempting to connect "
        "to the same destination {dst_ip}:{dst_port}. The repeated deny pattern was observed across "
        "{src_count} unique source IPs within the detection window. The firewall policy involved was "
        "{policy}, the service was {service}, and the Fortigate risk level was {crlevel}. "
        "This pattern may indicate internal scanning, lateral movement attempts, malware propagation, "
        "a misconfigured application/agent, or an unauthorized service trying to communicate on an uncommon port. "
        "Review the source IPs, destination asset, destination port, and firewall policy to confirm whether this "
        "is expected business traffic or suspicious blocked activity."
    ).format(
        dst_ip=dst_ip,
        dst_port=dst_port,
        src_count=len(source_ips),
        policy=policy,
        service=service,
        crlevel=crlevel
    )

    return message

def criticality():
    return "HIGH"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Non-Standard Port (T1571)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","destination_port","source_device_name"])

def correlationArtifacts():
    return ["source_ip","destination_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("destination_ip", "unknown"),
        "type": "ipaddress"
    }
