# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return ["host"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    proc = (event.get('process_name') or '').lower()
    parent = (event.get('parent_process_name') or '').lower()
    cmd = (event.get('command_line') or '').lower()

    key = application.get("system_discovery")

    # Prevent duplicate alerts
    if key is True:
        return 0.0

    if not proc:
        return 0.0

    discovery_cmds = [
        'systeminfo', 'whoami', 'hostname', 'ipconfig', 'net user'
    ]

    # Flexible match
    if not any(dc in proc for dc in discovery_cmds):
        return 0.0

    # Suspicious parents (strong signal)
    suspicious_parents = ['powershell', 'cmd', 'wscript', 'cscript']

    if parent and any(sp in parent for sp in suspicious_parents):
        application.put("system_discovery", True, 3600)
        return 0.50

    # Command chaining (recon behavior)
    if cmd and any(x in cmd for x in ['&', '&&']):
        application.put("system_discovery", True, 3600)
        return 0.50

    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    proc = event_data.get('process_name')
    parent = event_data.get('parent_process_name')
    host = event_data.get('host')
    user = event_data.get('user_name')

    context = "Potential system information discovery activity detected "

    if proc:
        context += "via command " + str(proc) + " "

    if parent:
        context += "spawned by " + str(parent) + " "

    if user:
        context += "executed by user " + str(user) + " "

    if host:
        context += "on host " + str(host) + " "

    context += "Such commands are commonly used by attackers during reconnaissance phases."

    return context

def criticality():
    return "MEDIUM"

def tactic():
    return "Discovery (TA0007)"

def technique():
    return "System Information Discovery (T1082)"

def artifacts():
    return stats.collect(["process_name","parent_process_name","command_line","user_name","host"])

def correlationArtifacts():
    return ["host"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
