# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    file_path = (event.get('file_path') or '').lower()
    command = (event.get('process_command') or '').lower()
    process = (event.get('process_name') or '').lower()
    user = str(event.get('user') or '')

    # Target file
    if '/etc/shadow' not in file_path and '/etc/shadow' not in command:
        return 0.0

    # Allowlist legitimate system processes
    legit_processes = [
        'passwd', 'chage', 'useradd', 'usermod',
        'login', 'sshd'
    ]

    if process in legit_processes:
        return 0.0

    # High confidence suspicious tools
    suspicious_tools = [
        'cat', 'cp', 'scp', 'rsync', 'wget', 'curl',
        'base64', 'tar', 'gzip'
    ]

    if any(tool in command for tool in suspicious_tools):
        return 1.0  # CRITICAL

    # Any non-root access is suspicious
    if user != '0':
        return 1.0

    # Any other access outside allowlist
    return 1.0


def clusters(event):

    return session.get("clusters")

def context(event):
    return (
        "Access to sensitive file /etc/shadow detected on host " + str(event_data.get('host')) +
        " by process " + str(event_data.get('process_name')) +
        " using command: " + str(event_data.get('process_command')) +
        ". This file contains password hashes and access may indicate credential dumping or privilege abuse."
    )

def criticality():
    return "CRITICAL"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "OS Credential Dumping (T1003)"

def artifacts():
    return stats.collect(["host","process_name","file_path"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "email"
    }
