# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_powershell_credential_access_activity_monitoring"

def automate():

    # automation: windows_powershell_credential_access_activity_monitoring
    return True

def notify():
    return False

def algorithm(event):
    if str(event.get("event_id") or "") != "4688":
        return 0.0

    process = str(event.get("process_name") or "").lower()
    cmd = str(event.get("command_line") or "").lower()

    if (
        "powershell.exe" not in process and
        "pwsh.exe" not in process
    ):
        return 0.0

    suspicious_keywords = [
        "iex",
        "invoke-expression",
        "downloadstring",
        "system.net.webclient",
        "invoke-webrequest",
        "iwr ",
        "wget ",
        "curl ",
        "-executionpolicy bypass",
        "-ep bypass",
        "-nop",
        "-noprofile",
        "start-bitstransfer",
        "frombase64string"
    ]

    for keyword in suspicious_keywords:
        if keyword in cmd:
            return 0.75

    return 0.0


def clusters(event):


    return session.get("clusterss")

def context(event):
    process = event.get("process_name") or "unknown"
    parent = event.get("parent_process_name") or "unknown"
    user = event.get("source_account_name") or "unknown"
    host = event.get("host") or "unknown"
    cmd = event.get("command_line") or "unavailable"

    return (
        "Suspicious PowerShell command execution detected. "
        "PowerShell process '{}' was launched by parent process '{}' "
        "under account '{}' on host '{}'. "
        "Observed command line: '{}'. "
        "The command contains suspicious PowerShell keywords commonly associated "
        "with script-based attacks, execution policy bypass attempts, payload "
        "retrieval, in-memory execution, or post-exploitation activity."
    ).format(
        process,
        parent,
        user,
        host,
        cmd
    )

def criticality():
    return "HIGH"

def tactic():
    return "Execution (TA0002)"

def technique():
    return "PowerShell (T1059/001)"

def artifacts():
    return stats.collect(["process_name","command_line","event_id","parent_process_name","host"])

def correlationArtifacts():
    return ["command_line","process_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
