PRIVILEGED_GROUPS = set([
    "Domain Admins",
    "Enterprise Admins",
    "Administrators",
    "Schema Admins",
    "Account Operators",
    "Backup Operators"
])
WHITELISTED_ACTORS = set([
    "Administrator",
    "SYSTEM",
    "svc_admin"
])

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_account_privilege_management"

def automate():

    # automation: windows_account_privilege_management
    return True

def notify():
    return False

def algorithm(event):
    event_id = str(event.get('event_id'))

    if event_id not in [
        '4728',
        '4732',
        '4756',
        '4729',
        '4733',
        '4757'
    ]:
        return 0.0

    group = str(
        event.get('destination_group_name') or ""
    ).strip()

    actor = str(
        event.get('source_account_name') or ""
    ).strip()

    if not group:
        return 0.0

    if group not in PRIVILEGED_GROUPS:
        return 0.0

    # ignore trusted admins
    if actor in WHITELISTED_ACTORS:
        return 0.0

    return 0.75


def clusters(event):




    return session.get("clusterss")

def context(event):
    action = (
        "added to"
        if str(event.get('event_id')) in [
            '4728',
            '4732',
            '4756'
        ]
        else "removed from"
    )

    return (
        "Privileged group membership modification detected on host '{host}'. "
        "User '{member}' was {action} privileged group '{group}' by account "
        "'{actor}'. Unauthorized changes to highly privileged Active Directory "
        "groups may indicate privilege escalation, persistence establishment, "
        "delegated administration abuse, or attempts to maintain elevated access "
        "within the environment."
    ).format(
        host=event.get('host', 'unknown'),
        member=event.get('member_name', 'unknown'),
        action=action,
        group=event.get('destination_group_name', 'unknown'),
        actor=event.get('source_account_name', 'unknown')
    )

def criticality():
    return "HIGH"

def tactic():
    return "Privilege Escalation (TA0004)"

def technique():
    return "Account Manipulation (T1098)"

def artifacts():
    return stats.collect(["member_name","event_id","source_account_name","destination_group_name"])

def correlationArtifacts():
    return ["source_account_name","member_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("member_name", "unknown"),
        "type": "group"
    }

