SENSITIVE_PATHS = (
    "\\hr\\",
    "\\finance\\",
    "\\payroll\\",
    "\\salary\\"
)

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["source_account_name"]

def investigate():
    return "windows_network_smb_dns_activity_monitoring"

def automate():

    # automation: windows_network_smb_dns_activity_monitoring
    return True

def notify():
    return False

def algorithm(event):

    if event.get("event_id") != "4663":
        return 0.0

    path = event.get("file_path")

    if not path:
        return 0.0

    path = path.lower()

    if not any(folder in path for folder in SENSITIVE_PATHS):
        return 0.0

    redkey = "unauthorized_access_to_sensitive_department_folders" 

    try:
        key = application.get(redkey)
    except Exception:
        key = None

    if key in (True, "true", "True"):
        return 0.0

    if stats.count("unauthorized_access_to_sensitive_department_folders_count") > 5:
        stats.resetcount("unauthorized_access_to_sensitive_department_folders_count")
        lock_acquired = application.putifabsent(redkey,True,86400)
        if lock_acquired:
          return 0.75

    return 0.0


def clusters(event):







    return session.get("clusterss")

def context(event):
    user = event.get("source_account_name")
    host = event.get("host")
    path = event.get("file_path")
    process = event.get("process_name")
    return (
        "Repeated access to sensitive department folders detected. "
        "User '{}' accessed '{}' using process '{}' on host '{}'. "
        "The accessed location matches a monitored HR, Finance, Payroll, "
        "Salary, or Compensation folder and exceeded the configured "
        "access threshold within a 5-minute period."
    ).format(
        user,
        path,
        process,
        host
    )

def criticality():
    return "HIGH"

def tactic():
    return "Collection (TA0009)"

def technique():
    return "Data from Information Repositories (T1213)"

def artifacts():
    return stats.collect(["host","file_path","event_id","source_account_name","process_name"])

def correlationArtifacts():
    return ["source_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }

