# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["source_ip"]

def investigate():
    return "windows_authentication_logon_anomalies"

def automate():

    # automation: windows_authentication_logon_anomalies
    return True

def notify():
    return False

def algorithm(event):

    # only failed logons
    if str(event.get("event_id")) != "4625":
        return 0.0

    process = (event.get("process_name") or "").lower()
    src_ip = event.get("source_ip")
    acct = (event.get("destination_account_name") or "").strip()
    status = (event.get("sub_status") or "").lower()
    logon_type = event.get("logon_type")

    # must be ADFS process
    if "microsoft.identityserver.servicehost.exe" not in process:
        return 0.0

    # ignore noise
    if not src_ip or src_ip in ["-", "UNKNOWN", "127.0.0.1", "::1"]:
        return 0.0

    if not acct or acct.endswith("$"):
        return 0.0

    # federation auth = network
    if logon_type not in ["3"]:
        return 0.0
    try:
        key = application.get("windows_adfs_authentication_abuse_via_failed_logons")
    except Exception:
        key = None

    if key in (True, "true", "True"):
        return 0.0

    if stats.count("adfs_failed_logons") > 8:
        stats.resetcount("adfs_failed_logons")
        lock_acquired = application.putifabsent("windows_adfs_authentication_abuse_via_failed_logons",True,86400)
        if lock_acquired:
          return 0.75

    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    src_ip = event.get("source_ip") or "unknown source"
    acct = event.get("destination_account_name") or "unknown account"
    host = event.get("host") or "unknown host"
    status = (event.get("sub_status") or "").lower()

    if status == "0xc000006a":
        reason = "incorrect password attempts"
    elif status == "0xc0000064":
        reason = "invalid or non-existent usernames"
    else:
        reason = "authentication failures"

    return (
        "Suspicious ADFS authentication failures detected from source IP "
        + str(src_ip)
        + " targeting account "
        + str(acct)
        + " on host "
        + str(host)
        + ". Repeated "
        + reason
        + " were observed via federation services, indicating possible identity probing "
        "or password spraying activity."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Brute Force (T1110)"

def artifacts():
    return stats.collect(["source_ip","destination_account_name","host","process_name","logon_type","event_id"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
