# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Store the session
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return ["source_ip","source_device_name"]

def investigate():
    return None

def automate():

    return True

def notify():
    return False

def algorithm(event):


    src_ip = event.get('source_ip')
    url = event.get('url')
    key = application.get("blocked_events")

    if key is True:
        return 0.0

    if not src_ip:
        return 0.0

    incidrrange = cidr.inRange(src_ip, [
        "14.141.115.58/30",
        "14.142.192.128/30",
        "125.17.69.248/30",
        "61.95.141.98/30",
        "203.194.111.106/32",
        "100.122.137.60/32",
        "100.76.126.248/32",
        "115.111.247.166/30",
        "103.176.170.64/29",
        "103.155.57.72/29",
        "14.140.210.208/30",
        "103.137.218.98/29",
        "122.185.181.54/30",
        "203.112.158.244/29",
        "103.26.201.244/29",
        "103.26.201.252/29",
        "103.26.201.0/24",
        "182.66.121.26/30",
        "14.97.152.142/30",
        "122.186.71.70/30",
        "14.143.159.224/30",
        "122.187.39.102/30",
        "203.122.8.200/29",
        "136.232.144.116/30",
        "136.232.142.132/30",
        "203.200.68.0/24",
        "14.140.162.248/29",
        "125.22.24.16/29",
        "115.112.32.192/29",
        "14.142.33.176/28",
        "59.160.104.0/24",
        "122.187.57.64/27",
        "47.29.213.16/29"
    ])

    if incidrrange:
        return 0.0

    log_subtype = event.get('log_subtype')

    if log_subtype == 'webfilter':
        if not url:
            return 0.0

        allowed_url = tpi.query("Whitelistedurls", "url = ?", [url])
        rows = allowed_url.get('rows') if allowed_url else []

        if rows:
            return 0.0

        allowed_url = [row[0] for row in rows]

        if (
            event.get('event_action') == 'blocked'
            and event.get('log_type') == 'utm'
            and url not in allowed_url
        ):
            # application.put("blocked_events", True, 86400)
            return 0.75

    if log_subtype == 'ssl':
        if event.get('event_action') == 'blocked' and event.get('log_type') == 'utm':
            application.put("blocked_events", True, 86400)
            return 0.75

    return 0.0


def clusters(event):



    """
    Store the session
    """
    return "initialization completed"

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """


    # Safely extract values with defaults
    device = event.get('source_device_name')
    source_ip = event.get('source_ip')
    destination_ip = event.get('destination_ip')
    destination_port = event.get('destination_port')
    policy_id = event.get('policy_id')
    protocol = event.get('network_protocol')
    action = event.get('event_action')
    details = event.get('event_details')
    log_type = event.get('log_type')
    log_subtype = event.get('log_subtype')

    message = (
        "The FortiGate device {device} detected '{action}' event for {log_type} actions with subtype {log_subtype} "
        "for source IP {source_ip}."
        "The most recent event shows a connection to {destination_ip}:{destination_port} "
        "because the firewall {details} using the {protocol} protocol. "
        "Such consistent blocking of outbound connections from a single user or host may indicate automated connection retries, "
        "credential-stuffing activity, or a misconfigured application repeatedly attempting disallowed traffic."
    ).format(
        device=device,
        action=action,
        log_type=log_type,
        source_ip=source_ip,
        protocol=protocol,
        destination_ip=destination_ip,
        destination_port=destination_port,
        details=details,
        log_subtype=log_subtype,
    )
    return message

def criticality():
    return "HIGH"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Application Layer Protocol (T1071)"

def artifacts():
    return stats.collect(["event_action","log_type","log_subtype","source_ip","destination_ip","destination_country","source_device_name","url"])

def correlationArtifacts():
    return ["source_ip","source_device_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "email"
    }
