# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """

    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "fortigate_threat_detections_and_preventions"

def automate():

    return True

def notify():
    return False

def algorithm(event):

    if (
      not event.get('network_request_method') or
      not event.get('event_action') or
      not event.get('event_category_desc')
    ):
        return 0.0

    network_request_method = (event.get("network_request_method")).lower()
    action = (event.get("event_action")).lower()
    category = (event.get("event_category_desc")).lower()

    blocked = action in ["blocked", "block", "deny", "denied", "dropped"]

    malicious_keywords = [
        "malicious",
        "phishing",
        "botnet",
        "command and control",
        "c2",
        "malware",
        "suspicious",
        "trojan"
    ]

    if (
        network_request_method == "domain"
        and blocked
        and any(k in category for k in malicious_keywords)
    ):
        return 0.75

    return 0.0


def clusters(event):




    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    source_device_name = event.get("source_device_name")
    user_name = event.get("user_name")
    source_ip = event.get("source_ip")
    destination_ip = event.get("destination_ip")
    url = event.get("url")
    event_category_desc = event.get("event_category_desc")
    network_request_method = event.get("network_request_method")
    event_action = event.get("event_action")
    event_details = event.get("event_details")

    return (
        "FortiGate device "
        + (source_device_name if source_device_name else "Unknown Device")
        + " detected an outbound request from source IP "
        + (source_ip if source_ip else "Unknown Source")
        + " associated with user "
        + (user_name if user_name else "Unknown User")
        + ". The request targeted "
        + (url if url else destination_ip if destination_ip else "Unknown Destination")
        + " and was categorized as "
        + (event_category_desc if event_category_desc else "Known Malicious Domain")
        + ". The request method was "
        + (network_request_method if network_request_method else "Unknown Method")
        + " and the firewall action taken was "
        + (event_action if event_action else "Unknown Action")
        + ". This indicates attempted communication with a known malicious domain that was blocked by FortiGate security controls."
        + (" Additional details: " + event_details + "." if event_details else "")
    )

def criticality():
    return "HIGH"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Application Layer Protocol (T1071)"

def artifacts():
    return stats.collect(["event_category_desc","event_action","source_device_name","source_ip","user_name"])

def correlationArtifacts():
    return ["source_ip","user_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
