# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return "30m"

def groupby():
    return ["source_account_name"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    event_category = str(event.get("event_category", "")).lower()

    threat_name = str(event.get("threat_name", "")).strip()

    if (event_category == "upload" and threat_name):

        stats.count("proofpoint_sensitive_upload_count")

        upload_count = int(stats.getcount("proofpoint_sensitive_upload_count") or 0)

        total_size = int(stats.sum("file_size") or 0)

        if (upload_count >= 10 and total_size >= 104857600):
            stats.resetcount("proofpoint_sensitive_upload_count")
            lock = application.putifabsent("proofpoint_high_volume_sensitive_transfer",True,1800)

            if lock:
                return 1.0

    return 0.0


def clusters(event):


    return session.get("clusters")

def context(event):
    try:
        total_size = int(stats.sum("file_size") or 0)

    except:
        total_size = 0

    return (
        "User '{0}' uploaded multiple files containing sensitive "
        "information. A cumulative total of '{1}' bytes was "
        "transferred within a 30-minute period. The uploaded "
        "content matched Proofpoint DLP classifications '{2}'. "
        "This activity may indicate bulk data movement, "
        "unauthorized sharing of corporate information, or "
        "potential data exfiltration."

    ).format(
      event.get("source_account_name","unknown"),
      total_size,
      event.get("threat_name","unknown"))

def criticality():
    return "CRITICAL"

def tactic():
    return "Exfiltration (TA0010)"

def technique():
    return "Automated Exfiltration (T1020)"

def artifacts():
    return stats.collect(["source_account_name","url","threat_name","file_name","file_size","destination_hostname"])

def correlationArtifacts():
    return ["source_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "username"
    }
