# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    if str(event.get('event_id')) == '4719':
        return 0.75
    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    return (
        "Audit policy was modified on host " +
        str(event.get('host')) +
        " by user " +
        str(event.get('source_account_name')) +
        "."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Defense Evasion (TA0005)"

def technique():
    return "Impair Defenses (T1562)"

def artifacts():
    return stats.collect(["host","source_account_name","event_id"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
