WHITELIST_ACCOUNTS = [
    "nt authority\\system","nt authority\\network service","nt authority\\local service",
    "system","localservice","networkservice",
    "backupsvc","svc_backup","veeam","veeamagent","commvault","veritas","arcserve",
    "dpmbackup","rubrik","cohesity",
    "crowdstrike","falcon","carbonblack","sentinelone","defender","sophos",
    "mcafee","trendmicro","symantec","eset","cybereason",
    "sccm","wsus","intune","pdqdeploy","landesk","altiris","tanium",
    "chef","puppet","ansible","jamf",
    "onedrive","sharepoint","dropbox","googledrive","nextcloud","owncloud",
    "synology","qnap",
    "svc_filecopy","svc_batch","svc_scheduledtask","svc_filesync",
    "svc_replication","svc_dbbackup","svc_maintenance","svc_monitor",
    "svc_orchestrator",
    "vmtools","vmware","hyperv","vcenter","svc_esxi","svc_vmbackup",
    "azureadconnect","adconnect","azurebackup","gmsa","svc_azureagent",
    "svc_msol","svc_adfs"
]
WHITELIST_LOWER = [w.lower() for w in WHITELIST_ACCOUNTS]

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "20m"

def groupby():
    return ["source_account_name"]

def investigate():
    return "windows_security_integrity_and_system_abuse_monitoring"

def automate():

    # automation: windows_security_integrity_and_system_abuse_monitoring
    return True

def notify():
    return False

def algorithm(event):

    evt_id = int(event.get("event_id") or 0)

    # Only relevant events
    if evt_id not in (4663, 5145, 4660):
        return 0.0
    acct = (event.get("source_account_name") or "").lower()
    if not acct or acct in ["-", "unknown"]:
        return 0.0

    if _is_whitelisted_account(acct):
        return 0.0



    # Only file server activity
    if not (event.get("share_name") or event.get("share_path")):
        return 0.0

    stat_key = "destructive_activity"

    # ✅ Strong signal → confirmed delete
    if evt_id == 4660:
        stats.count(stat_key)

    # ✅ Destructive actions (write/delete/rename)
    elif evt_id in (4663, 5145) and _is_destructive_action(event):
        stats.count(stat_key)

    else:
        return 0.0

    count = stats.getcount(stat_key)
    if count > 75:
        return 1.0

    return 0.0


def clusters(event):



    return session.get("clusters")

def context(event):
    acct = event.get("source_account_name") or "unknown"
    host = event.get("host") or "unknown"
    share = event.get("share_name") 
    file =  event.get("file_path")

    return (
        "Potential ransomware activity detected: User '%s' performed high-volume destructive "
        "file operations (delete/write/rename) on server '%s' (share='%s', sample='%s') "
        "within a 20-minute window."
        % (acct, host, share, file)
    )

def criticality():
    return "CRITICAL"

def tactic():
    return "Impact (TA0040)"

def technique():
    return "Data Encrypted for Impact (T1486)"

def artifacts():
    return stats.collect(["event_id","host","source_ip","source_port","source_account_name","share_name","share_path","target_relative_path","access_list_raw","access_mask_hex","source_process_name"])

def correlationArtifacts():
    return ["source_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }


def _is_destructive_action(event):
    # EventID check stays the same
    evt = str(event.get("event_id", ""))
    if evt not in ("4663", "5145"):
        pass

    # Avoid building one giant string and lowercasing it
    access_raw = str(event.get("access_list_raw") or "").lower()
    access_mask = str(event.get("access_mask_hex") or "").lower()
    access_reason = str(event.get("access_reason_detail") or "").lower()

    destructive_keywords = [
        "delete", "delete_child",
        "write", "write_data", "append_data",
        "rename", "set_ea",
        "generic_write", "create"
    ]

    # Scan fields individually (same logic, less overhead)
    for kw in destructive_keywords:
        if kw in access_raw or kw in access_mask or kw in access_reason:
            return True

    # Hex fallback unchanged
    if access_mask and "0x" in access_mask:
        return False

    return False
def _is_whitelisted_account(account):
    for w in WHITELIST_LOWER:
        if w in account:
            return True
    return False