# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "1m"

def groupby():
    return ["host","source_account_name"]

def investigate():
    return "windows_security_integrity_and_system_abuse_monitoring"

def automate():

    # automation: windows_security_integrity_and_system_abuse_monitoring
    return True

def notify():
    return False

def algorithm(event):
    # Normalize event id (use 0 if missing)
    evt_id = event.get('event_id')

    # Only care about printer config events 805 or 808
    if evt_id not in ["805", "808"]:
        return 0.0

    # Extract actor and host fields
    actor = event.get('source_account_name')
    host = event.get('host')

    # If actor missing, treat as suspicious
    if not actor:
        stats.count("printer_config_nonadmin")
        if stats.getcount("printer_config_nonadmin") > 0:
            return 0.75
        return 0.0

    # Define authorized admin tokens/identities (adjust to your environment)
    AUTH_ADMINS = ['ADMIN', 'ADMINISTRATOR', 'SYSTEM', 'PRINTADMIN', 'ITADMIN', 'SERVICE']

    actor_up = actor.upper()

    # If actor matches any authorized token substring, do not alert
    for tok in AUTH_ADMINS:
        if tok in actor_up:
            return 0.0

    # Otherwise count and alert
    stat_key = "printer_config_nonadmin"
    stats.count(stat_key)
    if stats.getcount(stat_key) > 0:
        return 0.75

    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    return "Printer configuration change (Event ID {}) on host '{}' by non-admin user '{}'".format(
        event.get("event_id", "UNKNOWN"),
        event.get("host", "UNKNOWN"),
        event.get("source_account_name", "UNKNOWN")
    )

def criticality():
    return "HIGH"

def tactic():
    return "Persistence (TA0003)"

def technique():
    return "Create or Modify System Process (T1543)"

def artifacts():
    return stats.collect(["event_id","host","source_account_name","process_name"])

def correlationArtifacts():
    return ["event_id","source_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }
