# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_security_integrity_and_system_abuse_monitoring"

def automate():

    # automation: windows_security_integrity_and_system_abuse_monitoring
    return True

def notify():
    return False

def algorithm(event):
    if event.get('event_id') == 4657 and 'Run' in event.get('registry_path'):
        return 0.75
    return 0.0


def clusters(event):


    return session.get("clusterss")

def context(event):
    return "Suspicious registry modification detected in " + event.get('registry_path')

def criticality():
    return "HIGH"

def tactic():
    return "Persistence (TA0003)"

def technique():
    return "Registry Run Keys / Startup Folder (T1547.001)"

def artifacts():
    return stats.collect(["host","registry_path","event_id"])

def correlationArtifacts():
    return ["registry_path","event_id"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
