# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Store the session
    """
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["destination_ip"]

def investigate():
    return "fortigate_network_traffic_anomaly_detection"

def automate():

    # automation: fortigate_network_traffic_anomaly_detection
    return True

def notify():
    return False

def algorithm(event):

    log_type = (event.get("log_type") or "").lower()
    action = (event.get("event_action") or "").lower()
    direction = (event.get("network_direction") or "").lower()
    key = application.get("inbound_con_spike")

    if key is True:
        return 0.0

    if log_type and log_type != 'traffic':
        return 0.0

    if direction and direction != 'inbound':
        return 0.0

    if action not in ['allow', 'accept', 'permit']:
        return 0.0

    if stats.count("inbound_connections") > 100:
        stats.resetcount("inbound_connections")
        lock_acquired = application.putifabsent("inbound_con_spike", True, 86400)
        if lock_acquired:
          return 0.75

    return 0.0


def clusters(event):











    """
    Store the session
    """
    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """




    return (
        "Spike in inbound connections detected targeting destination IP "
        + (event.get("destination_ip")) +
        ". A high number of incoming connections were observed within a short time 5 minute window, "
        "which may indicate scanning, brute-force attempts, or exploitation activity."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Initial Access (TA0001)"

def technique():
    return "Exploit Public-Facing Application (T1190)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","destination_port","network_protocol","event_action","log_type"])

def correlationArtifacts():
    return ["destination_ip"]

def huntingQueryTemplate():
    return """SELECT * FROM dictionary WHERE log_type = 'traffic' AND network_direction = 'inbound' AND event_action IN ('allow', 'accept', 'permit') AND destination_ip = '{{destination_ip}}'"""

def entity(event):
    return {
        "derived": False,
        "value": event.get("destination_ip", "unknown"),
        "type": "ipaddress"
    }
