# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "fortigate_session_analyser"

def automate():

    # automation: fortigate_session_analyser
    return True

def notify():
    return False

def algorithm(event):

    dst_ip = event.get('destination_ip')
    log_type = (event.get('log_type') or "").lower()
    action = (event.get('action') or "").lower()

    malicious_ip = tpi.query("MaliciousIP", "ip = ?", [dst_ip])

    if not malicious_ip or not malicious_ip.get('rows'):
        return 0.0

    malicious_ips = [row[0] for row in malicious_ip.get('rows', [])]


    if log_type in ['traffic', 'utm'] and action == 'accept' and dst_ip in malicious_ips:
        return 0.75

    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):

    # Safely extract values with defaults
    device = event_data.get('source_device_name')
    source_ip = event_data.get('source_ip')
    destination_ip = event_data.get('destination_ip')
    destination_port = event_data.get('destination_port')
    policy_id = event_data.get('policy_id')
    protocol = event_data.get('network_protocol')
    action = event_data.get('event_action') or event_data.get('action')
    app_name = event_data.get('applicationname')
    log_type = event_data.get('log_type')
    dest_country = event_data.get('destination_country')

    # Query threat intel feed for this destination IP
    malicious_ip_data = tpi.query("MaliciousIP", "ip = ?", [destination_ip])
    malicious_ip = None
    if malicious_ip_data and malicious_ip_data.get('rows'):
        malicious_ip = malicious_ip_data.get('rows')[0][0]

    # Build base message
    message = (
        "The FortiGate device {device} observed outbound {log_type} traffic that was '{action}' "
        "from source IP {source_ip} targeting the application '{app_name}'. "
        "The connection attempt to {destination_ip}:{destination_port} over {protocol} "
    ).format(
        device=device, action=action, log_type=log_type, source_ip=source_ip,
        app_name=app_name, destination_ip=destination_ip,
        destination_port=destination_port, protocol=protocol
    )

    if malicious_ip:
        message += "was confirmed malicious by the threat intelligence feed (Malicious IP: {0}). ".format(malicious_ip)
    else:
        message += "was directed towards a destination in {0}. ".format(dest_country )

    message += (
        "This may indicate command-and-control communication, data exfiltration, or other malicious outbound activity. "
    )

    return message

def criticality():
    return "HIGH"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Application Layer Protocol (T1071)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","destination_port","network_protocol","event_action","destination_country"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
