# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "windows_network_smb_dns_activity_monitoring"

def automate():

    # automation: windows_network_smb_dns_activity_monitoring
    return True

def notify():
    return False

def algorithm(event):
    if int(event.get("event_id") or 0) != 4663:
        return 0.0

    file_path = (event.get("file_path") or "").lower()
    access_mask = (event.get("access_mask") or "").lower()
    user = (event.get("source_account_name") or "").lower()

    # basic filters
    if not file_path.endswith(".exe"):
        return 0.0

    # write/create access (looser match)
    if not any(x in access_mask for x in ["0x2", "0x6", "0x100", "0x120"]):
        return 0.0

    # network share (UNC)
    if not file_path.startswith("\\\\"):
        return 0.0

    # optional: ignore system/service noise
    if user in ["system", "local service", "network service"]:
        return 0.0

    return 0.75


def clusters(event):



    return session.get("clusterss")

def context(event):
    file_path = (event.get('file_path') or event.get('object_name') or event.get('target_filename') or "<unknown-file>")
    host = event.get('host') 
    user = event.get('source_account_name')
    return (
        "Executable file upload detected. User '" + user +
        "' created or wrote an executable file at '" + file_path +
        "' on host '" + host + "'. This may indicate tool transfer or malware staging."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Ingress Tool Transfer (T1105)"

def artifacts():
    return stats.collect(["event_id","host","source_account_name","file_path"])

def correlationArtifacts():
    return ["source_account_name","file_path"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "accountname"
    }
