PASSWORD_RETRIEVAL_THRESHOLD = 10

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["user_name"]

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):

    key = application.get("excessive_password_retrieval")

    if key is True:
        return 0.0

    action = (event.get("event_action") or "").strip().lower()

    if action != "retrieve password":
        return 0.0

    if stats.count("password_retrievals") >= PASSWORD_RETRIEVAL_THRESHOLD:
        stats.resetcount("password_retrievals")
        lock_acquired = application.putifabsent("excessive_password_retrieval", True, 86400)
        if lock_acquired:
            return 0.75

    return 0.0


def clusters(event):

    return session.get("clusters")

def context(event):

    user = event.get("user_name") or "Unknown User"

    return (
        "User '{}' retrieved an unusually high number of privileged passwords "
        "within a short period. This behavior may indicate credential harvesting, "
        "account compromise, or unauthorized bulk access to privileged credentials."
    ).format(user)

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Credentials from Password Stores (T1555)"

def artifacts():
    return stats.collect(["user_name","source_ip","applicationname","event_action"])

def correlationArtifacts():
    return ["user_name"]

def huntingQueryTemplate():
    return ""

def entity(event):
    return {
        "derived": False,
        "value": event.get("user_name", "unknown"),
        "type": "user"
    }

