# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """

    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["source_ip"]

def investigate():
    return "windows_authentication_logon_anomalies"

def automate():

    # automation: windows_authentication_logon_anomalies
    return True

def notify():
    return False

def algorithm(event):
    src_ip = event.get('source_ip')
    acct = (event.get('destination_account_name') or "").strip()
    logon_type = event.get('logon_type')
    if not src_ip or src_ip in ["-", "UNKNOWN", "127.0.0.1", "::1"]:
        return 0.0
    if not acct or acct.endswith("$"):
        return 0.0


    if logon_type not in ["2", "3", "10"]:
        return 0.0

    try:
        key = application.get("password_spraying")
    except Exception:
        key = None

    if key in (True, "true", "True"):
        return 0.0

    if str(event.get('event_id')) == '4625':
        if stats.count('win_password_spray') > 10 :
            stats.resetcount('win_password_spray')
            lock_acquired = application.putifabsent("password_spraying",True,86400)
            if lock_acquired:
              return 0.75
    return 0.0


def clusters(event):





















    return session.get("clusterss")

def context(event):
    return (
        "Password spraying activity detected from source IP "
        + str(event.get('source_ip')) +
        ". Multiple failed logon attempts were observed across different user accounts "
        "within a short time window, indicating an attempt to guess passwords "
        "while avoiding account lockouts."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Password Spraying (T1110.003)"

def artifacts():
    return stats.collect(["source_ip","event_id","logon_type","host","destination_account_name","process_name"])

def correlationArtifacts():
    return ["source_ip"]

def huntingQueryTemplate():
    return """SELECT * FROM dictionary WHERE source_ip = '{{source_ip}}' AND event_id = '4625'"""

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
