# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    process = (event.get('process_name') or '').lower()
    command = (event.get('process_command') or '').lower()
    details = (event.get('event_details') or '').lower()
    dest_ip = event.get('destination_ip')

    reverse_patterns = [
        '/dev/tcp/',
        '>&',
        '0>&1',
        'bash -i',
        'nc -e',
        'netcat -e',
        'python -c',
        'perl -e'
    ]

    shell_processes = ['bash','sh','python','perl','nc','netcat']

    if dest_ip and (
        any(p in command for p in reverse_patterns) or
        any(p in details for p in reverse_patterns)
    ):
        return 1.0

    # fallback if process clearly shell + outbound socket
    if process in shell_processes and dest_ip and 'connect' in details:
        return 1.0

    return 0.0


def clusters(event):

    return session.get("clusters")

def context(event):
    return (
        "Possible reverse shell detected on host " + str(event_data.get('host')) +
        ". Process " + str(event_data.get('process_name')) + " by executing " + str(event_data.get('executable')) +
        " initiated outbound communication to " + str(event_data.get('destination_ip')) +
        ". This may indicate active attacker control."
    )

def criticality():
    return "CRITICAL"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Remote Access Software (T1219)"

def artifacts():
    return stats.collect(["host","process_name","destination_ip","user_id","executable","file_path","event_details"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "email"
    }
