# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    try:
        session.set("event", event)
        return "initialized"
    except Exception:
        return None

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):

    alert_type = (event.get("alert_type") or "").lower()

    malsite_category = (
        event.get("malsite_category") or ""
    ).lower()

    if (
        alert_type != "malsite"
        and "malicious site" not in malsite_category
    ):
        return 0.0

    severity = (event.get("event_severity") or "").lower()

    if severity == "low":
        return 0.25

    if severity == "poor":
        return 0.25

    if severity == "medium":
        return 0.50

    if severity == "high":
        return 0.75

    if severity == "critical":
        return 1.0

    return 0.75


def clusters(event):

    return []

def context(event):

    return (
        "Netskope detected access to a malicious site. "
        "User '{user}' from host '{host}' attempted to access "
        "domain '{domain}'. "
        "The request matched threat intelligence indicators and "
        "Netskope enforced action '{action}'."
    ).format(
        user=event.get("user_name", "unknown"),
        host=event.get("host", "unknown"),
        domain=event.get("destination_domain", "unknown"),
        action=event.get("action_type", "unknown")
    )

def criticality():

        event = session.get("event")

        severity = (event.get("event_severity") or "").lower()

        if severity == "critical":
            return "CRITICAL"

        if severity == "high":
            return "HIGH"

        if severity == "medium":
            return "MEDIUM"

        if severity == "low":
            return "LOW"

        if severity == "poor":
            return "LOW"

        return "MEDIUM"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Application Layer Protocol (T1071)"

def artifacts():
    return stats.collect(["host","user_name","source_ip","destination_ip","domain","url","applicationname","policy_name"])

def correlationArtifacts():
    return ["host","user_name","domain"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
